### ISSUE TITLE
Aborted builds rendered as Failing

### ISSUE THREAD

**Issue by dt** [jan-molak/jenkins-build-monitor-plugin#103]
The comment on https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/master/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobView.java#L27 seems to indicate that this was intentional, but, at least in our usage, that is not always the case (someone might abort to get next build to start sooner, for instance). Would be nice to render aborted as gray, as other jenkins views do, or be able to configure it.

Or, even, if someone was really ambitious, alternating gray and whatever color the previous build was.

**Comment by kthsieh** [comment]
Request++

In our case, we're having a problem where PhantomJS is periodically crashing when running on our Jenkins server, but runs fine on our laptops.  So passing means we're good, failing means someone broke a test, and aborted just means PhantomJS crashed on Jenkins again.  Would be nice to distinguish the three cases.

**Comment by zats** [comment]
I would back this issue, too, `aborted` is not necessarily as critical for all the teams.
I would probably add it to the options, but definitely mark it with a different class in HTML.

**Comment by r-ilott** [comment]
This definitely needs to be configurable if it gets added. Aborted builds absolutely need to be marked as failures for us!

**Comment by gabor-cs** [comment]
The best way would be if it's configurable. 
We abort the build (nightly test) if the HW resource is not available (booked by someone else). In our case abortion is not a failure.

**Comment by leemarmara** [comment]
We would definitely appreciate the cancelled builds being differentiated from failed ones.  It would stop my managed jumping up and down asking why no-one has claimed the 'broken' build and stop developers checking to see what the failure cause is.

The Radiator View used to display as grey and that was fine.  I don't mind what colour it is as long as it isn't red.
