### ISSUE TITLE
Show job as claimed if all test cases are claimed

### ISSUE THREAD

**Issue by kaihowl** [jan-molak/jenkins-build-monitor-plugin#111]
If a job is unstable, but all test cases have been claimed, display the whole job as claimed. (ENHANCEMENT)

**Comment by jan-molak** [comment]
Hi @kaihowl, is that still the case with [Claim plugin](https://wiki.jenkins-ci.org/display/JENKINS/Claim+plugin) v2.6?

**Comment by kaihowl** [comment]
I cannot comment on this, since we are not using this particular setup anymore. Sorry for not having any useful input.

**Comment by jan-molak** [comment]
OK, no worries. This seems to be fixed with Claim plugin version 2.6. If you experience this issue again please feel free to re-open the ticket!
