### ISSUE TITLE
Display order by last build time

### ISSUE THREAD

**Issue by Mercynary** [jan-molak/jenkins-build-monitor-plugin#113]
IMHO ordering the projects by name or  display name doesn't add much useful information. Wouldn't it be nice e.g. to have an order such as the projects by last build time. A simple additional Comparator such as the sample below would make the job.

```java
public class ByLastBuild implements Comparator<AbstractProject> {
    @Override
    public int compare(AbstractProject a, AbstractProject b) {
        return a.getLastBuild().getTimestamp().compareTo(b.getLastBuild().getTimestamp());
    }
}
```

**Comment by Brantone** [comment]
In some cases, where the monitor has 6+ jobs, having them bounce around by "last build time" would be confusing to have to search for one every time - as opposed to alphabetical and knowing which column/row it's in.
Having an option to do so would be a fair compromise.

**Comment by Mercynary** [comment]
It was meant as an additional option.

If there are many jobs that should be monitored, the monitor gets easily "crowded" or the single titles exceed their column. So it would be nice that the jobs are somehow ordered by their status (fail, unstable, stable) or their last build time.

**Comment by Brantone** [comment]
+1
Ah, gotcha, makes sense.

**Comment by jan-molak** [comment]
Sounds like a good idea :-) It should be fairly easy to add a new comparator - would you be happy to submit a pull request, @Mercynary?

**Comment by Mercynary** [comment]
Well I think I'll start with a new comparator in the next days.

**Comment by jan-molak** [comment]
Brilliant, looking forward to it, @Mercynary ! :+1:
