### ISSUE TITLE
Jenkins header and footer shows on some browsers

### ISSUE THREAD

**Issue by david-resnick** [jan-molak/jenkins-build-monitor-plugin#118]
I haven't been able to determine the exact circumstances where this occurs. but since upgrading from 1.594 to 1.596 some machines/browsers show the Jenkins header and footer in the Build Monitor view.

From what I've seen the problem occurs on Chrome and Safari, and looks fine on Firefox.

The screenshot below is of Safari on Mac OS X 10.10.

![build-monitor-bug](https://cloud.githubusercontent.com/assets/488086/5612418/7823f6f6-94dd-11e4-9f78-2165e20288b4.png)

**Comment by jan-molak** [comment]
Hi David and thanks for reporting this. Jenkins UI seems to be undergoing quite significant changes recently and this often breaks the plugins.
I managed to reproduce the issue you mentioned on Safari/Chrome/Firefox and Jenkins core 1.596  and prepared a fix that should alleviate it.

Would you mind grabbing the [latest build](https://smartcode-opensource.ci.cloudbees.com/job/jenkins-build-monitor-plugin/135/artifact/target/build-monitor-plugin.hpi) and letting me know if you're still experiencing the problem?

Thanks for your time and help!
Jan

**Comment by david-resnick** [comment]
Hi Jan,

In theory I have no problem testing the latest build, but in practice long running jobs make restarting the server a problem. I can put the hpi in place but I don't know when it will be loaded...

**Comment by jan-molak** [comment]
Hey David, that's fine, I appreciate your help. Let me know if it works fine for you (it does in my test environment) and I'll roll it out to Jenkins Update Centre.

**Comment by bernardomaciel** [comment]
Hi Jan,

I have just stumbled on the same issue.
Env: Chrome Version 39.0.2171.71 m on Win 7 64-bit.

With the last release (1.6+build.132), I have the same problem.
With the latest build you linked to above, the problem is solved.

Thanks for the fix!

Bernardo

P.S.: I would upload screenshots, but I am currently not able to :/
