### ISSUE TITLE
Where are jobs list of build-monitor dashboard saving ?

### ISSUE THREAD

**Issue by haplo31** [jan-molak/jenkins-build-monitor-plugin#123]
Hello,
I try to create multiple jobs by script and I don't want to have to check them all in my build-monitor config page.
Is there a file I can modify to add my new jobs in my build-monitor dashboard ?
I saw my list of jobs visible in build-monitor dashboard in config.xml file from Jenkins but it doesn't seem to have any effect when I add a job on this list, it doesn't appear on my build-monitor dashboard.
Thanks a lot for your help

**Comment by jan-molak** [comment]
Hey @haplo31 The configuration is saved in the config.xml file. If I remember correctly, this file is loaded when Jenkins starts up, so won't be reloaded if you change it manually after the startup. I think a restart would be required for your changes to take effect.

Hope this helps!
Jan

**Comment by haplo31** [comment]
Hi Jan,
Thanks for your answer, I find the configuration in the config.xml file and I am now able to add jobs by script.
You're right, the file is read on startup but I put a curl call in my job to reload configuration:
curl -X POST http://Username:Password@JenkinsIp:JenkinsPort/reload

**Comment by jan-molak** [comment]
Cool, glad I could help :)
