### ISSUE TITLE
Working with 200+ jobs on one screen

### ISSUE THREAD

**Issue by saan800** [jan-molak/jenkins-build-monitor-plugin#124]
We would like to display the status of 200+ jobs in our build monitor. 
I have tried to make the display with the smallest font and most number of columns, but there are still too many jobs to be able to see anything useful.

Build Monitor Plugin seems to try to fit all job panels onto the one screen without scrolling. But its makes it impossible to see anything.

If a "minimum" panel size could be set, and then let the page scroll, it would make this far more usable with a large number of jobs (especially combined with https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/86 - order by failed, unstable and successful)

![image](https://cloud.githubusercontent.com/assets/1147880/5740860/47761ba0-9bff-11e4-82bb-7cdc014d4d79.png)

**Comment by jan-molak** [comment]
Hi @saan800 and thanks for your feedback! That is indeed a busy screen! :smiley: 

The idea behind Build Monitor is that it should make it easy for one to understand the state of the project just from a quick glance at the screen. Having to scroll pretty much defeats this goal... But again, so does not being able to read the names...

I'm planning to start working on a new version of the UI soon to make working with large numbers of jobs easier on a single screen.

Perhaps in the meantime it might be worth reviewing the granularity of jobs you display on the screen?
* Are they all equally important? If you have too many low-level jobs displayed on one screen, consider consolidating them using [Promoted Builds Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Promoted+Builds+Plugin) or [MultiJob Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Multijob+Plugin)
* You can also use job filters: Build Monitor supports Jenkins [View Job Filters Plugin](https://wiki.jenkins-ci.org/display/JENKINS/View+Job+Filters), if you have it installed

I hope this helps!

Best,
Jan

**Comment by drekbour** [comment]
Hi, we have 200+ projects too. I made some changes to JBMP to allow dynamic filters inherited from the Jenkins ListView that backs it. 
We now only display running or failed jobs - an empty screen is good news. Here's the config
![image](https://cloud.githubusercontent.com/assets/2863082/8132853/71d36a32-111c-11e5-8c19-3cc8e587fcf2.png)

**Comment by drekbour** [comment]
Oh and I submitted a PR #57 to hide the header and footer. It has yet to be integrated but does a good job of reclaiming some vital pixels

**Comment by saan800** [comment]
Excellent - that will work nicely

**Comment by 75inchpianist** [comment]
If I were you, I would make a few seperate Monitor views that paginate your 200 + jobs.

Then open each view in a seperate tab.

Then write a script to switch tabs.

If on windows you can use this script that I use, otherwise the same I'm sure can be scripted in linux or whatever:

Set WScript.CreateObject("WScript.Shell")
Do While i=0
  WScript.Sleep(5000)
  WshShell.SendKeys "^{TAB}"
    `Wscript.Sleep(100)
    `WshShell.sendKeys "{F5}"
Loop

**Comment by drekbour** [comment]
The tab-switcher is useful for switching between different monitoring on a headsup screen (not just a Jenkins server)

@jan-molak Isn't this closable based on the authors comment. Perhaps a cookbook entry somewhere would provide a closure action.

**Comment by jan-molak** [comment]
Hey guys,

Please have a look at [the latest build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/lastSuccessfulBuild/artifact/target/build-monitor-plugin.hpi) and let me know your thoughts.

It contains a number of improvements as per your suggestions:
- the base font size is now calculated automatically based on the number of dashboard rows
- the user can still tweak the font size and make it up to 3x smaller or 2x larger than what's calculated automatically
- if the text doesn't fit the allocated space, it is wrapped to multiple lines
- if the number of displayed projects doesn't fit the screen, the dashboard becomes scrollable

@saan800 - I'd be grateful if you could share a screenshot of your Build Monitor after the [upgrade](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/13/artifact/target/build-monitor-plugin.hpi) (either on github or via [email](http://smartcodeltd.co.uk/contact/))

Best,
Jan
