### ISSUE TITLE
FYI I wrote an automated platform independant build for JBMP using docker / boot2docker

### ISSUE THREAD

**Issue by sirkkalap** [jan-molak/jenkins-build-monitor-plugin#127]
see: https://github.com/sirkkalap/jenkins-build-monitor-build-wrap
##

**Comment by jan-molak** [comment]
Haha, thanks @sirkkalap, that's pretty cool :) I need to try it out!

**Comment by sirkkalap** [comment]
There were some stupid errors in first versions (stdio-redirecting), but
now it seems to work (for me) :)


On Sat, Jan 24, 2015 at 8:02 PM, Jan Molak <notifications@github.com> wrote:

> Haha, thanks @sirkkalap <https://github.com/sirkkalap>, that's pretty
> cool :) I need to try it out!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/127#issuecomment-71329733>
> .
>



-- 
Petri Sirkkala, sirpete(ät)iki.fi, Skype: sirpete
+358 44 339 8668 // ...likes Gmail... //
