### ISSUE TITLE
Compiling the Code to create .war file on a NO INTERNET ENVIRONMENT

### ISSUE THREAD

**Issue by TathagatSwain** [jan-molak/jenkins-build-monitor-plugin#132]
Hi ,

I have to install Jenkins on a RHEL 6.5 machine and have to do it by compiling the source and the creating the war and then deploying it. Could you please help me as I am new to jenkins and tried to do it but couldnt. I have copied the tar.gz release   and also have maven on the system . But everytime that I try to use the command "mvn clean install -pl war -am -DskipTests" , it gives the following error :

"  Non-resolvable parent POM: Could not transfer artifact org.jenkins-ci:jenkins:pom:1.34 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): repo.jenkins-ci.org and 'parent.relativePath' points at wrong local POM @ line 28, column 11: Unknown host repo.jenkins-ci.org ->"

**Comment by jan-molak** [comment]
Hi @TathagatSwain,

[Jenkins CI](http://jenkins-ci.org/) and the [Build Monitor plugin](https://github.com/jan-molak/jenkins-build-monitor-plugin) are two separate projects. Jenkins CI that you're after is maintained by developers  you can contact via the [JenkinsCI-DEV google group](https://groups.google.com/forum/#!forum/jenkinsci-dev).

---

Having said that, it seems to me that the problem you're seeing might be related to your maven setup.
Make sure that you have the jenkins repo defined in your `~/.m2/settings.xml` if you want to build Jenkins or Jenkins plugins from scratch:

```
<settings>
  <pluginGroups>
    <pluginGroup>org.jenkins-ci.tools</pluginGroup>
  </pluginGroups>

  <profiles>
    <!-- Give access to Jenkins plugins -->
    <profile>
      <id>jenkins</id>
      <activation>
        <activeByDefault>true</activeByDefault> <!-- change this to false, if you don't like to have it on per default -->
      </activation>
      <repositories>
        <repository>
          <id>repo.jenkins-ci.org</id>
          <url>http://repo.jenkins-ci.org/public/</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>repo.jenkins-ci.org</id>
          <url>http://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
  <mirrors>
    <mirror>
      <id>repo.jenkins-ci.org</id>
      <url>http://repo.jenkins-ci.org/public/</url>
      <mirrorOf>m.g.o-public</mirrorOf>
    </mirror>
  </mirrors>
</settings>
```

Also following articles on the Jenkins Wiki might also be useful:
- https://wiki.jenkins-ci.org/display/JENKINS/Building+Jenkins
- https://wiki.jenkins-ci.org/display/JENKINS/Plugin+tutorial

Hope this helps,
Jan
