### ISSUE TITLE
Order jobs by other than name ? 

### ISSUE THREAD

**Issue by janolaveide** [jan-molak/jenkins-build-monitor-plugin#133]
It would be nice to be able to sort jobs by the time they ran so that the most recently executed jobs appear first.

**Comment by TASSDevon** [comment]
I'd like to be given the freedom to order the jobs in any way I want, that be really great as well.

Request++

**Comment by sahlawat1** [comment]
Request++

**Comment by jan-molak** [comment]
Hi guys and thanks for your feedback! There's already a ticket raised for that feature - #37

Current version of Build Monitor supports ordering jobs using custom comparators from the [buildmonitor/order](https://github.com/jan-molak/jenkins-build-monitor-plugin/tree/master/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/order) package. 
If you'd like to submit a pull request with more comparators I'd be happy to merge it! :smiley: 
Custom comparators should be fairly straight-forward to add, have a look at [this commit](https://github.com/jan-molak/jenkins-build-monitor-plugin/commit/d01494c3b776de6b4048a95da580af8eb1e88027) for example.
