### ISSUE TITLE
Mvn clean package error

### ISSUE THREAD

**Issue by RZhou94** [jan-molak/jenkins-build-monitor-plugin#140]
I have an error when i try to do mvn clean package
I am using Windows 8, 
With jdk-1.7.0.75
node.js 0.10.38
npm 1.4.28
and maven 3.0.5

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/AppliesVSCT/DevHome/Project/EclipseWS/jenkins-build-monitor-plugin/s
rc/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobViewTe
st.java:[440,9] no suitable method found for assertThat(java.util.List<java.lang
.String>,java.lang.String)
    method org.junit.Assert.<T>assertThat(T,org.hamcrest.Matcher<? super T>) is
not applicable
      (no instance(s) of type variable(s) T exist so that argument type java.lan
g.String conforms to formal parameter type org.hamcrest.Matcher<? super T>)
    method org.junit.Assert.<T>assertThat(java.lang.String,T,org.hamcrest.Matche
r<? super T>) is not applicable
      (cannot instantiate from arguments because actual and formal argument list
s differ in length)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7:26.889s
[INFO] Finished at: Tue Apr 21 14:54:34 CEST 2015
[INFO] Final Memory: 36M/107M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
1:testCompile (default-testCompile) on project build-monitor-plugin: Compilation
 failure
[ERROR] /D:/AppliesVSCT/DevHome/Project/EclipseWS/jenkins-build-monitor-plugin/s
rc/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobViewTe
st.java:[440,9] no suitable method found for assertThat(java.util.List<java.lang
.String>,java.lang.String)
[ERROR] method org.junit.Assert.<T>assertThat(T,org.hamcrest.Matcher<? super T>)
 is not applicable
[ERROR] (no instance(s) of type variable(s) T exist so that argument type java.l
ang.String conforms to formal parameter type org.hamcrest.Matcher<? super T>)
[ERROR] method org.junit.Assert.<T>assertThat(java.lang.String,T,org.hamcrest.Ma
tcher<? super T>) is not applicable
[ERROR] (cannot instantiate from arguments because actual and formal argument li
sts differ in length)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by RZhou94** [comment]
I tried to skip all tests. And jenkins run after this skips, 

But i am not sure what is the right solution.

mvn clean package -DskipTests -Dmaven.test.skip=true

**Comment by jan-molak** [comment]
Hey @RZhou94, no skipping the tests is definitely not a right solution :-) They should all be passing if the environment is correctly set up. I'll close this ticket so we can continue our conversation here: #141 as it seems to be the same problem.
