### ISSUE TITLE
Workflow Jenkins Plugin builds support

### ISSUE THREAD

**Issue by valldeck** [jan-molak/jenkins-build-monitor-plugin#143]
It would be great to provide Workflow Jenkins Plugin builds compatibility.

**Comment by jan-molak** [comment]
Ah, interesting! What functionality would you like to see exactly?

**Comment by valldeck** [comment]
Overall compatibility. Your plugin provide ability to add workflow jobs to the list, but unfortunately these builds are not visible on diagram.

Workflow plugin authors say: (https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md): "For architectural reasons, plugins providing various extensions of interest to builds cannot be made automatically compatible with Workflow. Typically they require use of some newer APIs, large or small."

Workflow plugin is absolutely hot now and it would be great to monitor workflow tasks with your software.

**Comment by jan-molak** [comment]
Closing for now as Build Monitor now allows for Workflow Projects to be displayed.

**Comment by RudolfVonKrugstein** [comment]
It does not work for me, I get this error:

```
javax.servlet.ServletException: java.lang.ClassCastException: org.jenkinsci.plugins.workflow.job.WorkflowJob cannot be cast to hudson.model.AbstractProject
```

**Comment by jan-molak** [comment]
Hey @RudolfVonKrugstein - what version of Jenkins, Build Monitor and the Pipeline plugin are you using? Also, would you mind pasting the full stack trace as well as it would help with trying to understand the problem?

Thanks!
J
