### ISSUE TITLE
Build Monitor plugin shows error as below 

### ISSUE THREAD

**Issue by vshah2422** [jan-molak/jenkins-build-monitor-plugin#144]
"\n\n\n\n    \n    <!DOCTYPE html><html><head resURL=\"/static/972290de\">\n    \n\n    <title>Jenkins [Jenkins]</title><link rel=\"stylesheet\" href=\"/static/972290de/css/style.css\" type=\"text/css\" /><link rel=\"stylesheet\" href=\"/static/972290de/css/color.css\" type=\"text/css\" /><link rel=\"stylesheet\" href=\"/static/972290de/css/responsive-grid.css\" type=\"text/css\" /><link rel=\"shortcut icon\" href=\"/static/972290de/favicon.ico\" type=\"image/vnd.microsoft.icon\" /><script>var isRunAsTest=false; var rootURL=\"\"; var resURL=\"/static/972290de\";</script><script src=\"/static/972290de/scripts/prototype.js\" type=\"text/javascript\"></script><script src=\"/static/972290de/scripts/behavior.js\" type=\"text/javascript\"></script><script src='/adjuncts/972290de/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src=\"/static/972290de/scripts/yui/yahoo/yahoo-min.js\"></script><script src=\"/static/972290de/scripts/yui/dom/dom-min.js\"></script><script src=\"/static/972290de/scripts/yui/event/event-min.js\"></script><script src=\"/static/972290de/scripts/yui/animation/animation-min.js\"></script><script src=\"/static/972290de/scripts/yui/dragdrop/dragdrop-min.js\"></script><script src=\"/static/972290de/scripts/yui/container/container-min.js\"></script><script src=\"/static/972290de/scripts/yui/connection/connection-min.js\"></script><script src=\"/static/972290de/scripts/yui/datasource/datasource-min.js\"></script><script src=\"/static/972290de/scripts/yui/autocomplete/autocomplete-min.js\"></script><script src=\"/static/972290de/scripts/yui/menu/menu-min.js\"></script><script src=\"/static/972290de/scripts/yui/element/element-min.js\"></script><script src=\"/static/972290de/scripts/yui/button/button-min.js\"></script><script src=\"/static/972290de/scripts/yui/storage/storage-min.js\"></script><script src=\"/static/972290de/scripts/hudson-behavior.js\" type=\"text/javascript\"></script><script src=\"/static/972290de/scripts/sortable.js\" type=\"text/javascript\"></script><script>crumb.init(\"\", \"\");</script><link rel=\"stylesheet\" href=\"/static/972290de/scripts/yui/container/assets/container.css\" type=\"text/css\" /><link rel=\"stylesheet\" href=\"/static/972290de/scripts/yui/assets/skins/sam/skin.css\" type=\"text/css\" /><link rel=\"stylesheet\" href=\"/static/972290de/scripts/yui/container/assets/skins/sam/container.css\" type=\"text/css\" /><link rel=\"stylesheet\" href=\"/static/972290de/scripts/yui/button/assets/skins/sam/button.css\" type=\"text/css\" /><link rel=\"stylesheet\" href=\"/static/972290de/scripts/yui/menu/assets/skins/sam/menu.css\" type=\"text/css\" /><link rel=\"search\" href=\"/opensearch.xml\" type=\"application/opensearchdescription+xml\" title=\"Jenkins\" /><meta name=\"ROBOTS\" content=\"INDEX,NOFOLLOW\" /><script src=\"/adjuncts/972290de/org/kohsuke/stapler/jquery/jquery.full.js\" type=\"text/javascript\"></script><script>var Q=jQuery.noConflict()</script><script src=\"/static/972290de/scripts/yui/cookie/cookie-min.js\"></script></head><body id=\"jenkins\" class=\"yui-skin-sam jenkins-1.609\" data-version=\"jenkins-1.609\"><a href=\"#skip2content\" class=\"skiplink\">Skip to content</a><div id=\"page-head\"><div id=\"header\"><div class=\"logo\"><a id=\"jenkins-home-link\" href=\"/\"><img src=\"/static/972290de/images/headshot.png\" alt=\"title\" id=\"jenkins-head-icon\" /><img src=\"/static/972290de/images/title.png\" alt=\"title\" width=\"139\" id=\"jenkins-name-icon\" height=\"34\" /></a></div><div class=\"login\"> <a href=\"/login?from=%2Foops\"><b>log in</b></a></div><div class=\"searchbox hidden-xs\"><form method=\"get\" name=\"search\" action=\"/search/\" style=\"position:relative;\" class=\"no-json\"><div id=\"search-box-minWidth\"></div><div id=\"search-box-sizer\"></div><div id=\"searchform\"><input name=\"q\" placeholder=\"search\" id=\"search-box\" class=\"has-default-text\" /> <a href=\"http://wiki.jenkins-ci.org/display/JENKINS/Search+Box\"><img src=\"/static/972290de/images/16x16/help.png\" style=\"width: 16px; height: 16px; \" class=\"icon-help icon-sm\" /></a><div id=\"search-box-completion\"></div><script>createSearchBox(\"/search/\");</script></div></form></div></div><div id=\"breadcrumbBar\"><tr id=\"top-nav\"><td id=\"left-top-nav\" colspan=\"2\"><link rel='stylesheet' href='/adjuncts/972290de/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/972290de/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class=\"top-sticker noedge\"><div class=\"top-sticker-inner\"><div id=\"right-top-nav\"></div><ul id=\"breadcrumbs\"><li class=\"item\"><a href=\"/\" class=\"model-link inside\">Jenkins</a></li><li href=\"/\" class=\"children\"></li></ul><div id=\"breadcrumb-menu-target\"></div></div></div></td></tr></div></div><div id=\"page-body\"><div class=\"row\"><div id=\"side-panel\"><div id=\"side-panel-content\"><div class=\"task\"><a href=\"http://jenkins-ci.org/\" class=\"task-icon-link\"><img src=\"/static/972290de/images/24x24/next.png\" style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-next icon-md\" /></a> <a href=\"http://jenkins-ci.org/\" class=\"task-link\">Jenkins project</a></div><div class=\"task\"><a href=\"http://issues.jenkins-ci.org/\" class=\"task-icon-link\"><img src=\"/static/972290de/images/24x24/gear2.png\" style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-gear2 icon-md\" /></a> <a href=\"http://issues.jenkins-ci.org/\" class=\"task-link\">Bug tracker</a></div><div class=\"task\"><a href=\"http://jenkins-ci.org/content/mailing-lists\" class=\"task-icon-link\"><img src=\"/static/972290de/images/24x24/search.png\" style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-search icon-md\" /></a> <a href=\"http://jenkins-ci.org/content/mailing-lists\" class=\"task-link\">Mailing Lists</a></div><div class=\"task\"><a href=\"https://twitter.com/jenkinsci\" class=\"task-icon-link\"><img src=\"/static/972290de/images/24x24/user.png\" style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-user icon-md\" /></a> <a href=\"https://twitter.com/jenkinsci\" class=\"task-link\">Twitter: @jenkinsci</a></div></div></div><div id=\"main-panel\"><div id=\"main-panel-content\"><a name=\"skip2content\"></a><h1 style=\"text-align: center\"><img src=\"/static/972290de/images/rage.png\" width=\"154\" height=\"179\" /><span style=\"font-size:50px\"> Oops!</span></h1><div id=\"error-description\"><p>A problem occurred while processing the request.\n        Please check <a href=\"https://issues.jenkins-ci.org/\">our bug tracker</a> to see if a similar problem has already been reported.\n        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.\n        If you think this is a new issue, please file a new issue.\n        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.\n        <a href=\"http://jenkins-ci.org/content/mailing-lists\">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style=\"margin:2em; clear:both\">java.lang.IllegalStateException: WRITER\r\n\tat org.eclipse.jetty.server.Response.getOutputStream(Response.java:691)\r\n\tat javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:142)\r\n\tat org.kohsuke.stapler.compression.CompressionServletResponse.activate(CompressionServletResponse.java:61)\r\n\tat org.kohsuke.stapler.compression.CompressionFilter.activate(CompressionFilter.java:108)\r\n\tat org.kohsuke.stapler.ResponseImpl.getCompressedOutputStream(ResponseImpl.java:285)\r\n\tat org.kohsuke.stapler.jelly.DefaultScriptInvoker.createOutputStream(DefaultScriptInvoker.java:88)\r\n\tat org.kohsuke.stapler.jelly.DefaultScriptInvoker.createXMLOutput(DefaultScriptInvoker.java:68)\r\n\tat org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:51)\r\n\tat org.kohsuke.stapler.jelly.JellyFacet$1.dispatch(JellyFacet.java:95)\r\n\tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)\r\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)\r\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)\r\n\tat hudson.init.impl.InstallUncaughtExceptionHandler$1.reportException(InstallUncaughtExceptionHandler.java:27)\r\n\tat org.kohsuke.stapler.compression.CompressionFilter.reportException(CompressionFilter.java:77)\r\n\tat org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:55)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)\r\n\tat hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)\r\n\tat org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\r\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\r\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\r\n\tat org.eclipse.jetty.server.Server.handle(Server.java:370)\r\n\tat org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)\r\n\tat org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)\r\n\tat org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)\r\n\tat org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)\r\n\tat org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)\r\n\tat org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)\r\n\tat org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)\r\n\tat org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)\r\n\tat winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n</pre></div></div></div></div></div><div id=\"footer-container\" class=\"hidden-xs\"><div id=\"footer\"><span class=\"page_generated\">\n          Page generated:\n          Apr 27, 2015 11:03:37 AM</span><span class=\"rest_api\"><a href=\"api/\">REST API</a></span><span class=\"jenkins_ver\"><a href=\"http://jenkins-ci.org/\">Jenkins ver. 1.609</a></span><div id=\"l10n-dialog\" class=\"dialog\"></div><div id=\"l10n-footer\" style=\"display:none; float:left\"><a href=\"#\" onclick=\"return showTranslationDialog();\"><img src=\"/static/972290de/plugin/translation/flags.png\" />\n      Help us localize this page\n    </a></div><script>var footer = document.getElementById('l10n-footer');\n    var f = document.getElementById('footer');\n    f.insertBefore(footer,f.firstChild);\n    footer.style.display=\"block\";\n\n    var translation={}; \n    translation.bundles = \"sHHeEG3vsGunFQUdwkncbhucVwj294br25y6N3iF95L0ZyUuUVj4QmTdesqWHFCTbijkgslWTPxDja1WpkUJm2THY6m0X9g7c06b3DwPptAn4PhSL2Sd95Yqd+ZHBO/39ufvd7jJEMV+42+eJqaB35KwvDuCbBw3vg2sAjkfYzZy7+QNA3AdXb53p9IT5gk1USXnE263bJllKzggB4cmdiTjask8wbWNb/BPU4qZ5dkGOniXSonzph0H8LktnwjCIpFt3ydprp8R5sVKY6YDgQTBWhlWQvsT11aWAO+T7dXT4sluCGz992v3ssBlN9UYKBhBxW0eFk8zMVLued1hh4AzfcPJJAXhZj/bwimmlyzP/L5X17unbrI04JpqN0AOhVDWsSeNpkyQb+qjI3VKJzodw/abNi88SHL4BdorkEfoDbGxYNpIIw+k2NJrHtSIYZsF/M8H9UH3Rh8pYBv3l3SSC/+3Bgv9rXPJRgcC3qk=\";\n    translation.detectedLocale = \"\";\n\n    function showTranslationDialog() {\n      if(!translation.launchDialog)\n        loadScript(\"/static/972290de/plugin/translation/dialog.js\");\n      else\n        translation.launchDialog();\n      return false; \n    }</script></div></div></body></html>"

**Comment by jan-molak** [comment]
Hi @vshah2422 and thanks for submitting this report.

In order for me to help you I need a bit more information:
- what version of Build Monitor plugin and Jenkins are you using?
- are you running Jenkins stand-alone or delpoyed to a container (ie. Tomcat)?
- what other Jenkins plugins do you have installed? I'd be interested to know if you're using the Build Failure Analyzer, Claim plugin or the View Filters plugin (and their versions)
- what were you trying to do when you encountered the problem?

Best,
Jan

**Comment by vshah2422** [comment]
Hi Jan,

Please see below answers.


1)      Version for build monitor plugin :- 1.6+build.142

2)      I have installed Jenkins stand-alone and its running from Jenkins.war file with the batch file I have to Open the war file so its like everytime we need to open Jenkins we need to have command prompt open that will run Jenkins.war.  I have that setup from last 3 years.

3)      Yes I have installed all 3 plugins as I saw that dependency for build monitor plugin. However they are option but I thought let me install them so I did install them yesterday and their versions are

è Build Failure analyser :- 1.13.0

è Claim Plugin :-2.6

è View filter plugin :- 1.26


4)      Issue is happening after configuring jobs for showing on dashboard when I try to go there its showing me that popup.


[cid:image006.png@01D08197.AA101590]



Let me know if you need any more info.

Thanks
Viral

**Comment by vshah2422** [comment]
Hi Jan,

I found the problem and fixed it as it was not working due to Claim build plugin. So after uninstallation it works . So don’t know if you need to fix it anything from your end or not ?


Viral Shah | Quality Assurance (Automation)

Level 2, 509 St Kilda Road | Melbourne VIC 3004 | Australia

T 61 3 9828 9517 | F 61 3 9820 9258

[facebook-icon]<https://www.facebook.com/WebjetAU>[google-icon]<https://plus.google.com/+WebjetAU/>[linkedin-icon]<http://www.linkedin.com/company/webjet-com-au/>


E vshah@webjet.com.au<mailto:vshah@webjet.com.au>


[Logo-Email-Signature]<http://www.webjet.com.au/>[Zuji-signature]<http://www.zuji.com.au/>

From: Viral Shah
Sent: Tuesday, 28 April 2015 9:43 AM
To: 'jan-molak/jenkins-build-monitor-plugin'; jan-molak/jenkins-build-monitor-plugin
Subject: RE: [jenkins-build-monitor-plugin] Build Monitor plugin shows error as below (#144)

Hi Jan,

Please see below answers.


1)      Version for build monitor plugin :- 1.6+build.142

2)      I have installed Jenkins stand-alone and its running from Jenkins.war file with the batch file I have to Open the war file so its like everytime we need to open Jenkins we need to have command prompt open that will run Jenkins.war.  I have that setup from last 3 years.

3)      Yes I have installed all 3 plugins as I saw that dependency for build monitor plugin. However they are option but I thought let me install them so I did install them yesterday and their versions are

è Build Failure analyser :- 1.13.0

è Claim Plugin :-2.6

è View filter plugin :- 1.26


4)      Issue is happening after configuring jobs for showing on dashboard when I try to go there its showing me that popup.


[cid:image006.png@01D0819C.E027A440]



Let me know if you need any more info.

Thanks
Viral

**Comment by jan-molak** [comment]
Hey Viral and thanks for letting me know.

It's possible that the version of Jenkins you're using broke some APIs that Claim Plugin relies on.
I usually recommend going with Long Term Support (LTS, a.k.a. stable) releases of Jenkins Core rather than the latest build as they tend to cause fewer problems.

Best,
Jan
