### ISSUE TITLE
Feature Request: Support Playing Audio Notifications

### ISSUE THREAD

**Issue by taylormathewson** [jan-molak/jenkins-build-monitor-plugin#147]
Build Monitor is a great visualization plugin, but it would be great to have audio capabilities as well.

One approach may be to integrate with the Sounds Jenkins plugin.  https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Sounds+plugin

Thanks for considering this.

**Comment by jan-molak** [comment]
Thanks for your feedback, @taylormathewson. I like the idea :smiley: 
In fact it's already been requested here: #24 

I'll close this ticket, but please feel free to comment on #24. I haven't considered using [Jenkins Sounds Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Sounds+plugin) as my understanding of it was that it only supported server-side sounds (which is not particularly useful if your Jenkins server sits in a data centre on the other side of the globe), but I see they're supporting browser sounds too.

**Comment by taylormathewson** [comment]
Ugh, I really did try searching.  Thanks for replying, I'll comment there.

**Comment by jan-molak** [comment]
No worries, thanks for posting the comment :)
