### ISSUE TITLE
Change font size does not seem to work in IE.

### ISSUE THREAD

**Issue by Tallmaris** [jan-molak/jenkins-build-monitor-plugin#149]
I am dragging the slider but nothing happens in IE.

**Comment by jan-molak** [comment]
Hello there! A bit more context would be extremely helpful :)
What are the versions of:
- IE
- Build Monitor
- Jenkins

you're using, please?

**Comment by Tallmaris** [comment]
Hi there,

Jenkins is ver. 1.549
The plugin is 1.6+build.142
IE is 11 (v. 11.0.9600.17728)

**Comment by jan-molak** [comment]
Thanks @Tallmaris, I'l have a look.
By the way, did you notice any errors in the [IE11 JavaScript console](https://msdn.microsoft.com/en-us/library/bg182326(v=vs.85).aspx) ?

**Comment by Tallmaris** [comment]
Hi Jan,

I will double check tomorrow when I'm at work but I don't remember noticing anything out of the ordinary.
L.

**Comment by jan-molak** [comment]
Hey @Tallmaris - it looks like you're correct - the slider responsible for changing the size of the font doesn't work in IE11 on Windows; The second one doing the columns works correctly though.
Thanks for reporting the issue!

Can you use any alternative browser while I'm working on getting this resolved?

**Comment by Tallmaris** [comment]
Oh yes absolutely. :)

**Comment by jan-molak** [comment]
Cool :-) I need to get this slider component replaced as it's holding back upgrading to a newer version of Angular anyway.
