### ISSUE TITLE
Sorry to bother you, but Jenkins is having a problem :-(

### ISSUE THREAD

**Issue by pmapkiranch** [jan-molak/jenkins-build-monitor-plugin#154]
Hello I am getting this error when I click on Build Status tab after upgrading to Jenkins Version 1.616

Instead of an expected response I received the following, which usually means an internal Jenkins error:

"\n\n\n\n    \n    <!DOCTYPE html><html><head resURL=\"/static/34b19185\">\n    \n\n    <title>Jenkins [Jenkins]</title><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/34b19185/css/style.css\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/34b19185/css/color.css\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/34b19185/css/responsive-grid.css\" /><link rel=\"shortcut icon\" type=\"image/vnd.microsoft.icon\" href=\"/static/34b19185/favicon.ico\" /><script>var isRunAsTest=false; var rootURL=\"\"; var resURL=\"/static/34b19185\";</script><script src=\"/static/34b19185/scripts/prototype.js\" type=\"text/javascript\"></script><script src=\"/static/34b19185/scripts/behavior.js\" type=\"text/javascript\"></script><script src='/adjuncts/34b19185/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src=\"/static/34b19185/scripts/yui/yahoo/yahoo-min.js\"></script><script src=\"/static/34b19185/scripts/yui/dom/dom-min.js\"></script><script src=\"/static/34b19185/scripts/yui/event/event-min.js\"></script><script src=\"/static/34b19185/scripts/yui/animation/animation-min.js\"></script><script src=\"/static/34b19185/scripts/yui/dragdrop/dragdrop-min.js\"></script><script src=\"/static/34b19185/scripts/yui/container/container-min.js\"></script><script src=\"/static/34b19185/scripts/yui/connection/connection-min.js\"></script><script src=\"/static/34b19185/scripts/yui/datasource/datasource-min.js\"></script><script src=\"/static/34b19185/scripts/yui/autocomplete/autocomplete-min.js\"></script><script src=\"/static/34b19185/scripts/yui/menu/menu-min.js\"></script><script src=\"/static/34b19185/scripts/yui/element/element-min.js\"></script><script src=\"/static/34b19185/scripts/yui/button/button-min.js\"></script><script src=\"/static/34b19185/scripts/yui/storage/storage-min.js\"></script><script src=\"/static/34b19185/scripts/hudson-behavior.js\" type=\"text/javascript\"></script><script src=\"/static/34b19185/scripts/sortable.js\" type=\"text/javascript\"></script><script>crumb.init(\"\", \"\");</script><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/34b19185/scripts/yui/container/assets/container.css\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/34b19185/scripts/yui/assets/skins/sam/skin.css\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/34b19185/scripts/yui/container/assets/skins/sam/container.css\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/34b19185/scripts/yui/button/assets/skins/sam/button.css\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/34b19185/scripts/yui/menu/assets/skins/sam/menu.css\" /><link title=\"Jenkins\" rel=\"search\" type=\"application/opensearchdescription+xml\" href=\"/opensearch.xml\" /><meta name=\"ROBOTS\" content=\"INDEX,NOFOLLOW\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"/plugin/html-audio-notifier/css/client.css\" /><script src=\"/plugin/html-audio-notifier/scripts/cookies.js\" type=\"text/javascript\"></script><script src=\"/plugin/html-audio-notifier/scripts/utils.js\" type=\"text/javascript\"></script><script src=\"/plugin/html-audio-notifier/scripts/client.js\" type=\"text/javascript\"></script><script src=\"/plugin/html-audio-notifier/scripts/player.js\" type=\"text/javascript\"></script><script type=\"text/javascript\">window.HTML5NotifierPlugin = window.HTML5NotifierPlugin || {};\n    window.HTML5NotifierPlugin.enabled = true;\n    window.HTML5NotifierPlugin.queryTimeout = 10;\n    window.HTML5NotifierPlugin.notificationTimeout = 15000;\n    window.HTML5NotifierPlugin.jenkinsrooturl = '';\n    window.HTML5NotifierPlugin.resURL  = '/static/34b19185';</script><script src=\"/plugin/html5-notifier-plugin/js/notify.js\" type=\"text/javascript\"></script><script src=\"/plugin/html5-notifier-plugin/js/html5-notifier.js\" type=\"text/javascript\"></script></head><body id=\"jenkins\" data-version=\"jenkins-1.616\" class=\"yui-skin-sam jenkins-1.616\"><a href=\"#skip2content\" class=\"skiplink\">Skip to content</a><div id=\"page-head\"><div id=\"header\"><div class=\"logo\"><a id=\"jenkins-home-link\" href=\"/\"><img id=\"jenkins-head-icon\" alt=\"title\" src=\"/static/34b19185/images/headshot.png\" /><img id=\"jenkins-name-icon\" height=\"34\" alt=\"title\" width=\"139\" src=\"/static/34b19185/images/title.png\" /></a></div><div class=\"login\"> <a href=\"/login?from=%2Foops\"><b>log in</b></a>\n    |\n    <a href=\"/signup\"><b>sign up</b></a></div><div class=\"searchbox hidden-xs\"><form style=\"position:relative;\" name=\"search\" action=\"/search/\" class=\"no-json\" method=\"get\"><div id=\"search-box-minWidth\"></div><div id=\"search-box-sizer\"></div><div id=\"searchform\"><input id=\"search-box\" placeholder=\"search\" name=\"q\" class=\"has-default-text\" /> <a href=\"http://wiki.jenkins-ci.org/display/JENKINS/Search+Box\"><img style=\"width: 16px; height: 16px; \" class=\"icon-help icon-sm\" src=\"/static/34b19185/images/16x16/help.png\" /></a><div id=\"search-box-completion\"></div><script>createSearchBox(\"/search/\");</script></div></form></div></div><div id=\"breadcrumbBar\"><tr id=\"top-nav\"><td id=\"left-top-nav\" colspan=\"2\"><link rel='stylesheet' href='/adjuncts/34b19185/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/34b19185/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class=\"top-sticker noedge\"><div class=\"top-sticker-inner\"><div id=\"right-top-nav\"></div><ul id=\"breadcrumbs\"><li class=\"item\"><a class=\"model-link inside\" href=\"/\">Jenkins</a></li><li class=\"children\" href=\"/\"></li></ul><div id=\"breadcrumb-menu-target\"></div></div></div></td></tr></div></div><div id=\"page-body\"><div class=\"row\"><div id=\"side-panel\"><div id=\"side-panel-content\"><div class=\"task\"><a class=\"task-icon-link\" href=\"http://jenkins-ci.org/\"><img style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-next icon-md\" src=\"/static/34b19185/images/24x24/next.png\" /></a> <a class=\"task-link\" href=\"http://jenkins-ci.org/\">Jenkins project</a></div><div class=\"task\"><a class=\"task-icon-link\" href=\"http://issues.jenkins-ci.org/\"><img style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-gear2 icon-md\" src=\"/static/34b19185/images/24x24/gear2.png\" /></a> <a class=\"task-link\" href=\"http://issues.jenkins-ci.org/\">Bug tracker</a></div><div class=\"task\"><a class=\"task-icon-link\" href=\"http://jenkins-ci.org/content/mailing-lists\"><img style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-search icon-md\" src=\"/static/34b19185/images/24x24/search.png\" /></a> <a class=\"task-link\" href=\"http://jenkins-ci.org/content/mailing-lists\">Mailing Lists</a></div><div class=\"task\"><a class=\"task-icon-link\" href=\"https://twitter.com/jenkinsci\"><img style=\"width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;\" class=\"icon-user icon-md\" src=\"/static/34b19185/images/24x24/user.png\" /></a> <a class=\"task-link\" href=\"https://twitter.com/jenkinsci\">Twitter: @jenkinsci</a></div></div></div><div id=\"main-panel\"><div id=\"main-panel-content\"><a name=\"skip2content\"></a><h1 style=\"text-align: center\"><img height=\"179\" width=\"154\" src=\"/static/34b19185/images/rage.png\" /><span style=\"font-size:50px\"> Oops!</span></h1><div id=\"error-description\"><p>A problem occurred while processing the request.\n        Please check <a href=\"https://issues.jenkins-ci.org/\">our bug tracker</a> to see if a similar problem has already been reported.\n        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.\n        If you think this is a new issue, please file a new issue.\n        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.\n        <a href=\"http://jenkins-ci.org/content/mailing-lists\">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style=\"margin:2em; clear:both\">java.lang.IllegalStateException: WRITER\r\n\tat org.eclipse.jetty.server.Response.getOutputStream(Response.java:691)\r\n\tat javax.servlet.ServletResponseWrapper.getOutputStream(ServletResponseWrapper.java:142)\r\n\tat org.kohsuke.stapler.compression.CompressionServletResponse.activate(CompressionServletResponse.java:61)\r\n\tat org.kohsuke.stapler.compression.CompressionFilter.activate(CompressionFilter.java:108)\r\n\tat org.kohsuke.stapler.ResponseImpl.getCompressedOutputStream(ResponseImpl.java:285)\r\n\tat org.kohsuke.stapler.jelly.DefaultScriptInvoker.createOutputStream(DefaultScriptInvoker.java:88)\r\n\tat org.kohsuke.stapler.jelly.DefaultScriptInvoker.createXMLOutput(DefaultScriptInvoker.java:68)\r\n\tat org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:51)\r\n\tat org.kohsuke.stapler.jelly.JellyFacet$1.dispatch(JellyFacet.java:95)\r\n\tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)\r\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)\r\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)\r\n\tat hudson.init.impl.InstallUncaughtExceptionHandler$1.reportException(InstallUncaughtExceptionHandler.java:27)\r\n\tat org.kohsuke.stapler.compression.CompressionFilter.reportException(CompressionFilter.java:77)\r\n\tat org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:55)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)\r\n\tat hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)\r\n\tat org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\r\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\r\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\r\n\tat org.eclipse.jetty.server.Server.handle(Server.java:370)\r\n\tat org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)\r\n\tat org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)\r\n\tat org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)\r\n\tat org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)\r\n\tat org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)\r\n\tat org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)\r\n\tat org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)\r\n\tat org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)\r\n\tat winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n</pre></div></div></div></div></div><div id=\"footer-container\" class=\"hidden-xs\"><div id=\"footer\"><span class=\"page_generated\">\n          Page generated:\n          08-Jun-2015 12:12:38</span><span class=\"rest_api\"><a href=\"api/\">REST API</a></span><span class=\"jenkins_ver\"><a href=\"http://jenkins-ci.org/\">Jenkins ver. 1.616</a></span><div id=\"htmlAudioNotifierPanel\" class=\"isDisabled\"><a class=\"enableControl\" title=\"Click to enable audio notifications\" href=\"#\" onclick=\"htmlAudioNotifierClient.toggle(); return false;\"><div class=\"htmlAudioDisabled\">Disabled</div></a><a class=\"disableControl\" title=\"Click to disable audio notifications\" href=\"#\" onclick=\"htmlAudioNotifierClient.toggle(); return false;\"><div class=\"htmlAudioEnabled\">Enabled</div></a></div><script type=\"text/javascript\">htmlAudioNotifierClient = new HtmlAudioNotifierClient(\n            'http://build:8080/',\n            document.getElementById('htmlAudioNotifierPanel')\n        );</script><button style=\"display: none\" id=\"btn-html5-notifier-activate\">Enable Notifications</button></div></div></body></html>"

**Comment by jan-molak** [comment]
Hello there and thanks for reporting the issue.

The error you're seeing looks like a bug in Jenkins, or one of the plugins Build Monitor relies on.
A similar (or maybe same?) issue has been raised on the Jenkins bug tracking system already as [JENKINS-28102](https://issues.jenkins-ci.org/browse/JENKINS-28102).
@daniel-beck is asking there for more information on the error you should be able to see in the Jenkins log.

Speaking of which, did you perhaps see any errors in the [Jenkins error log](https://wiki.jenkins-ci.org/display/JENKINS/Logging)?

Also, are you using the [Claim plugin](https://wiki.jenkins-ci.org/display/JENKINS/Claim+plugin) and if so, what version are you on? The latest one available is 2.7. If you're on an earlier one it would be good if you could upgrade it.

BTW: please bear in mind that I recommend using a [Long Term Support release](https://jenkins-ci.org/changelog-stable) of Jenkins rather than the ["latest and greatest"](https://jenkins-ci.org/changelog) as they are more stable.

**Comment by jan-molak** [comment]
@pmapkiranch, I'll close this ticket for now as it seems more Jenkins- than Build Monitor-related. 
Please feel free to re-open it if that's not the case.
