### ISSUE TITLE
If Jenkins is down, try refreshing automatically until it works

### ISSUE THREAD

**Issue by lhahne** [jan-molak/jenkins-build-monitor-plugin#161]
We are currently running unattended radiators. Whenever a Jenkins server goes down, build monitor displays a message that connection has been lost and instructs you to refresh the page, and then we need to manually refresh it once Jenkins is back up. It would be a lot nicer, if build monitor would poll Jenkins every 30 s or so and detect when it is back up and recover automatically.

**Comment by mk-stp** [comment]
We have an issue that is somewhat connected. Once in a while we get 504 in response to ajax request and it makes the plugin stop refreshing. Exception shouldn't prevent the next refresh event.

**Comment by jan-molak** [comment]
@mk-stp it seems like a problem with a http proxy you might have in front of Jenkins? Perhaps #150 could be useful as @marc-guenther and I had a good conversation about proxies there.

@lhahne That's a good point, #150 suggests how error handling could be enhanced to cater for this scenario. If you have the time to submit a pull request it would be awesome :) If not I'll add this ticket to [the backlog](https://waffle.io/jan-molak/jenkins-build-monitor-plugin) and look into it as soon as I can.

**Comment by davidparsson** [comment]
#166 may be remotely related

**Comment by jan-molak** [comment]
Fixed with #197
