### ISSUE TITLE
Show failed tests count / total tests count for test jobs

### ISSUE THREAD

**Issue by benoit808** [jan-molak/jenkins-build-monitor-plugin#162]

**Comment by jan-molak** [comment]
Hi @benoit808 - to see the number of failing tests please install the Build Failure Analyzer plugin as per the [FAQ](https://github.com/jan-molak/jenkins-build-monitor-plugin/wiki/FAQ#how-do-i-know-what-tests-failed-the-build) (and ticket #99)

**Comment by benoit808** [comment]
Wow, shame on me for missing it in the FAQ and most of all for forgetting that I already brought this up and got a response for it.

Thank you for pointing out the solution

**Comment by jan-molak** [comment]
No worries; what this shows is that the docs should be improved further so that they're easier to find :)
