### ISSUE TITLE
Infinite reloading when accessing a Build Monitor view via custom domain

### ISSUE THREAD

**Issue by davidparsson** [jan-molak/jenkins-build-monitor-plugin#166]
Consider a Jenkins instance which is accessible on two different URLs:
- One that is accessible both publicly on the internet and on the same network as the Jenkins server, `https://jenkins.acme.com/`. Note: `https`.
- One that is only accessible from the local network, `http://jenkins/`. Note: `http`.

The Jenkins URL in Jenkins' settings is configured to be `https://jenkins.acme.com/`.

If accessing a Build Monitor view via the other domain, for example `http://jenkins/view/build-monitor/`, the Ajax request to `http://jenkins/$stapler/bound/.../fetchJobViews` is a 404. This makes the Build Monitor view believe that Jenkins is restarting, making it reload itself. Since Jenkins is not restarting, this happens over and over again.

It would be nice to have this working on a non-configured domain as well, or at least show a message instead of an infinite reload loop.

I'm on Jenkins 1.565.3 LTS.

**Comment by traviscosgrave** [comment]
I am using: Jenkins ver. 1.650 with Build Monitor version 1.8+build.201601112328.

I can confirm similar behaviour. Custom URL on https, and reload loop due to 404 error thrown by the $stapler endpoint.

Looking at what I think are the relative logs, I'm happy to add more if there are other useful locations:

```
Processing request for /$stapler/bound/25d7b4e0-5d72-49fa-bd26-682690c50ab1/fetchJobViews
Feb 29, 2016 1:14:21 PM FINE org.kohsuke.stapler.Dispatcher
-> evaluate(<org.kohsuke.stapler.bind.BoundObjectTable@3697fbf9> :org.kohsuke.stapler.bind.BoundObjectTable,"/25d7b4e0-5d72-49fa-bd26-682690c50ab1/fetchJobViews")
Feb 29, 2016 1:14:21 PM FINE org.kohsuke.stapler.Dispatcher
-> evaluate(((StaplerFallback)<org.kohsuke.stapler.bind.BoundObjectTable@3697fbf9>).getStaplerFallback(),"/25d7b4e0-5d72-49fa-bd26-682690c50ab1/fetchJobViews")
Feb 29, 2016 1:14:21 PM FINE org.eclipse.jetty.io.nio.ChannelEndPoint
oshut SCEP@618a5859{l(/10.0.10.100:57958)<->r(/10.0.10.170:8080),s=1,open=true,ishut=false,oshut=false,rb=false,wb=false,w=true,i=0r}-{AsyncHttpConnection@41ae6d16,g=HttpGenerator{s=4,h=0,b=0,c=-1},p=HttpParser{s=2,l=113,c=2},r=1}
Feb 29, 2016 1:14:21 PM FINE org.eclipse.jetty.security.authentication.FormAuthenticator
auth deferred 1l6nacqm4cjoe1hfmzgy8a72pg
Feb 29, 2016 1:14:21 PM FINE org.eclipse.jetty.server.Server
RESPONSE /$stapler/bound/25d7b4e0-5d72-49fa-bd26-682690c50ab1/fetchJobViews  404 handled=true
```
I get the same result regardless of login status.

The strange thing is that, if I leave the page to continue restarting for a while ~400-1000 seconds, then the endpoint resolves properly for that session.

I'm not familiar with the jenkins plugin system and stapler, but could there be a race condition where the url generated is old, or creating a new session? Or the long time to get logged in just so happens to work because something goes fast enough or slow enough that the dynamic url is finally valid?

The request looks like this as copied as cURL from chrome inspector:

```
curl 'https://jenkins.mydomain.com/$stapler/bound/dfb58add-04d5-4046-a81f-0f89151b91cd/fetchJobViews' -H 'origin: https://jenkins.mydomain.com' -H 'accept-encoding: gzip, deflate' -H 'accept-language: en-CA,en;q=0.8,en-US;q=0.6' -H 'crumb: 9bccad19-7a4c-4d1d-afa6-fff6b9c632a7' -H 'cookie: JSESSIONID.07af8a39=12xy39ql8hoixdwnt0nwp8700; _gat=1; _ga=GA1.2.2145061769.1456769811' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36' -H 'content-type: application/x-stapler-method-invocation;charset=UTF-8' -H 'accept: application/json, text/plain, */*' -H 'cache-control: max-age=0' -H 'authority: jenkins.mydomain.com' -H 'referer: https://jenkins.mydomain.com/view/Testing%20Jobs%20-%20Monitor/' -H '.crumb: 9bccad19-7a4c-4d1d-afa6-fff6b9c632a7' --data-binary '[]' --compressed --insecure
```

I don't see any chances when it starts to work. Although it doesn't always start to work.

**Comment by traviscosgrave** [comment]
I finally had the request I was watching, and the id in the `/$stapler/bound/{id}/fetchJobViews` changed when it started to work. I took about 350 seconds for that to update. I was running the inspection with Chrome's cache disabled. I'll check if there were any intermediate caches that may have continued to return the wrong URL. I haven't found the place where that URL is generated yet, so it's a little hard to trace.

**Comment by traviscosgrave** [comment]
We use nginx to offload ssl and load balance. Caching was turned on for our jenkins server. I guess the request was improperly getting cached by nginx (although this seems to be new behaviour). Disabling the caching on nginx repaired the issue.

**Comment by TobiX** [comment]
Maybe add

    <st:setHeader name="Expires" value="0" />
    <st:setHeader name="Cache-Control" value="no-cache,no-store,must-revalidate" />

to the index.jelly? It seems that is the default for all other Jenkins pages:

https://github.com/jenkinsci/jenkins/blob/20cb8fdde819ab6a00140f6c987bb9dddaff7483/core/src/main/resources/lib/layout/html.jelly#L56
