### ISSUE TITLE
BM view does not show any jobs

### ISSUE THREAD

**Issue by coosminus** [jan-molak/jenkins-build-monitor-plugin#171]
hi, I just installed the plugin in Jenkins 1.609.2. I created a view, selected a few jobs and save, but nothing is shown. Any ideas?

**Comment by jan-molak** [comment]
Hi there, @coosminus! Could you please provide some additional details to help me diagnose the issue:
- which version of Build Monitor are you using?
- what types of jobs did you select to be displayed? (freestyle, maven, workflow, ...)
- are there any errors in the Jenkins log?
- I'm also not sure what you mean by "nothing is shown"? Would you mind pasting a screenshot?

Best,
J

**Comment by coosminus** [comment]
Hi Jan,

I did some more testing and found out that there is only one job that when I select it the plugin does not show any jobs (just the empty grey background, see attachment). If I remove this job then plugin works just fine.
![image](https://cloud.githubusercontent.com/assets/14057692/9601158/2420c08c-50a0-11e5-84ac-4ad6e1835bd2.png)

The "problematic" job is gerrit repo job, but basically is a simple trigger job that triggers many other jobs underneath
- plugin version: 1.6+build.156
- I haven't seen any errors in logs related to this

**Comment by jan-molak** [comment]
Interesting, thanks for the addtional details. Did you notice any errors in the JavaScript console by any chance?

**Comment by coosminus** [comment]
Nope unfortunately I don;t see any errors in the JS console.

**Comment by jan-molak** [comment]
Hmm, that's quite bizarre.. And you're sure that the JS console is enabled before you go to the build monitor screen so that no errors get lost? Have you tried enabling the console and refreshing the page? This should help catch any potential errors.

Also, if even when doing the above no errors show up it might be worth looking at the response produced by the
`https://your-jenkins-instance/jenkins/$stapler/bound/.../fetchJobViews` end point.
Would you mind pasting it please?

**Comment by coosminus** [comment]
Remote Address:10.124.9.221:443
Request URL:https://<<jenkins>>/$stapler/bound/fc21e3f5-cac1-4b4c-8bb0-45d6c2a2c153/fetchJobViews
Request Method:POST
Status Code:504 Gateway Time-out
Response Headers
view source
Connection:keep-alive
Content-Length:584
Content-Type:text/html
Date:Thu, 03 Sep 2015 12:32:26 GMT
Server:nginx/1.6.2
Request Headers
view source
.crumb:ec2f0ff8-eb52-44da-9348-070e2ffe095b
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:2
Content-Type:application/x-stapler-method-invocation;charset=UTF-8
Cookie:s_fid=45CD1CF07163D7A5-18959D760BA52DC3; s_prop56=49; __utma=60088625.173589735.1437569136.1437569136.1437569136.1; __utmz=60088625.1437569136.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); AMCV_E16CD4415481B5550A4C98A2%40AdobeOrg=432708069%7CMCMID%7C26854205778418695731893284304661258614%7CMCAAMLH-1439295846%7C6%7CMCAAMB-1439295846%7Chmk_Lq6TPIBMW925SPhw3Q; jenkins-timestamper=system; jenkins-timestamper-local=false; jenkins-timestamper-offset=-7200000; screenResolution=1920x1200; JSESSIONID.2f4fa4b6=1jxaguw07fo96z0x1ird3tehi
Crumb:ec2f0ff8-eb52-44da-9348-070e2ffe095b
Host:<<my jenkins>>
Origin:https://<<my jenkins>>
Referer:https://<<my jenkins>>/view/BM-view/
User-Agent:Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by Dudssource** [comment]
Hi, I had the same issue when monitoring a job which was building in a slave machine, but in my case the problem was with the "View Job Filters" plugin. When I switched to the default "Job Filters" configuration my problem was gone.
I hope this helps.

**Comment by marcosrocha85** [comment]
Hello, same issue here. I just noticed that the dashboard becomes empty when it's building Java complex systems on Maven. I don't noticed if it turns empty when Maven runs any test suite, but if I am not wrong, this situation appears since when my projects hadn't test suite.

**Comment by jan-molak** [comment]
It's possible that the problem you're seeing is connected with #181 I've [just released](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases/tag/v1.6%2Bbuild.162) a fix for.

Please let me know if the issue still occurs after upgrading to the latest version.

Best,
Jan

**Comment by jan-molak** [comment]
Closing as this issue should be addressed by [1.6+build.162](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases/tag/v1.6%2Bbuild.162).
