### ISSUE TITLE
How to modify the polling interval ?

### ISSUE THREAD

**Issue by bigmyx** [jan-molak/jenkins-build-monitor-plugin#173]
Hello,
I have noticed the Monitor polling the Jenkins every second.
Can I configure this polling interval ? 
If yes - now ?
Thanks !

**Comment by jan-molak** [comment]
Hi there, @bigmyx! 

Build Monitor polls Jenkins [once every five seconds](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/c59fc30777767887f4af443a123c65ac9489ed81/src/main/webapp/scripts/controllers.js#L13) and this is currently not configurable. Is there any particular reason why you think it should poll Jenkins less/more often?

Best,
J

**Comment by jan-molak** [comment]
Closing the ticket due to inactivity. If this functionality is still needed - please let me know.

**Comment by guoliang** [comment]
Our Jenkins becomes very slow and sometime also unresponsive. 

Do you think it could be because this plugin is polling every five seconds? We have dedicated monitor which switch between two pages which display this plugin. So basically it does two request every five seconds.

**Comment by ilor** [comment]
@jan-molak in one instance I'm seeing high jenkins load caused by multiple people having multiple tabs with build monitor open (some of those tabs are helper pages with multiple build monitors in iframes). Would be nice to have this interval configurable.

**Comment by DimitarTodorov** [comment]
Hi @jan-molak , 
Is there any update on this issue. I'm also experiencing a high load of our jenkins and configuring the option for polling interval will be a great feature.
