### ISSUE TITLE
Add support for displaying parallel job execution

### ISSUE THREAD

**Issue by DanEngelbrecht** [jan-molak/jenkins-build-monitor-plugin#174]
Very happy with the first look at you build monitor.

However, in our setup we run jobs in parallel with different parameters. Currently the build monitor just presents the latest started build and any feedback of the first running build is lost.

It would be awesome if parallel builds was detected and presented inside a "block", perhaps splitting it vertically?
##

**Comment by erikhakansson** [comment]
This would be very nice.

**Comment by jivimberg** [comment]
+1

**Comment by Linkinou** [comment]
+1

**Comment by matthiasvegh** [comment]
+1

**Comment by jan-molak** [comment]
Thanks for the feedback, @DanEngelbrecht! That would be a cool feature, I agree! I'd be happy to help out if anyone would like to start a pull request?
