### ISSUE TITLE
Configurable overscan compensation.

### ISSUE THREAD

**Issue by apfelfabrik** [jan-molak/jenkins-build-monitor-plugin#175]
When using this monitor on a couple of big screens w/ Chromecasts, there is an overscan issue w/ some of the TVs, cutting off the corners of the picture. For a project that performs so well on big screens it would be really great if there was an overscan compensation, just like the configurable font, perhaps like a slider up to 5%?

**Comment by jan-molak** [comment]
Sounds like a cool idea and it seems like you already have implementation in mind! Maybe a pull request? :smiley:

**Comment by luebbe** [comment]
Isn't overscan normally handled either in the TV configuration or in the graphics driver settings? The second option is surely not possible on chromecasts :-)

**Comment by jan-molak** [comment]
Hey @apfelfabrik, is this ticket closable based on the @luebbe's comment?

**Comment by jan-molak** [comment]
Closing based on @luebbe comment; please +1 if it's still needed and I'll reopen it.
