### ISSUE TITLE
Plugin does not work in IE

### ISSUE THREAD

**Issue by SmokyNight** [jan-molak/jenkins-build-monitor-plugin#176]
When I open dashboard in IE9 I can see only background image and no data there. Note, that this is not permission problem(different message appears, if you lack permission to view this page).
Environment:
Windows server
Jenkins 1.576
Plugin version: 1.6+build.140 
IE9

**Comment by jan-molak** [comment]
Hi there @SmokyNight, please note that IE9 does not support CSS3 flexbox, which the Build Monitor requires as explained in the [readme file](https://github.com/jan-molak/jenkins-build-monitor-plugin#browser-support---modern-web-browsers-only).

Please consider upgrading your IE to at least version 10 or using any other [modern web browser](http://caniuse.com/#feat=flexbox).

Hope this helps!
