### ISSUE TITLE
Reporting: Display test results and/or code coverage when the build is done

### ISSUE THREAD

**Issue by luebbe** [jan-molak/jenkins-build-monitor-plugin#178]
Hi folks,

I like the idea of how jenkins build results can be visualized using dashing. For example: https://gist.github.com/akalyaev/6391422. 

Would it be possible to display an additional metric when the build is finished? e.g.
- class coverage in %
- line coverage in %
- successful unit tests in %

This could be achieved using a different colour/structure combination than the one used while the build is running. Maybe something like this:
![coveragesuggest2](https://cloud.githubusercontent.com/assets/3872576/10604737/db1dce5e-7726-11e5-8e12-cfbebdbe05c5.png)

What do you think?
##

**Comment by arpitgold** [comment]
+1 
It will be a nice feature and a value add too. :+1:

**Comment by astrosuf** [comment]
This would be a really handy feature! instead of a green or red a balance to show some passed some failed with coverage details.

**Comment by diogoeag** [comment]
+1

I think that number of failed tests could also be interesting. Projects with lots of tests will have very small percentage of failing tests.

**Comment by juperala** [comment]
+1. In many cases having only Green/Red/Yellow build in radiator does not show the full picture.  It would be useful to know either % or amount of tests failed vs. test run. E.g. , "8 / 160 tests failed" or "95% of tests passed."

Alternatively build monitor could include similar view like Jenkins Test Trend Chart showing passed/failed/skipped test statistics from job executions.

**Comment by jan-molak** [comment]
I like the Test Trend Chart/Sparkline idea - pull requests are very welcome :-)

**Comment by emiller12** [comment]
+1 Coverage display on completed builds would be great.

**Comment by jalanga** [comment]
+1

**Comment by DSBalaban** [comment]
Agreed. It would be awesome to have this. +1

**Comment by fattouchsquall** [comment]
+1

**Comment by jan-molak** [comment]
Not as glamorous as the example provided by @luebbe (yet!), but the coverage could be displayed using a build badge. Please see #258 and the [release notes](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases/tag/v1.11%2Bbuild.201701152243) for more details.

Hope this helps,
Jan

Ps.
If it doesn't help - please do let me know ;-)

**Comment by luebbe** [comment]
Very cool! I'll try it out ASAP :)
