### ISSUE TITLE
Enable/Disable the fading colors for ongoing jobs

### ISSUE THREAD

**Issue by fredrikand** [jan-molak/jenkins-build-monitor-plugin#184]
When using the monitor in our landscape, some seems to think that the fading colors are disturbing. Especially when we have 20+ jobs displayed that run in parallel.
We wish to have the possibility to configure the fading on/off.

Ref:
https://issues.jenkins-ci.org/browse/JENKINS-30406

**Comment by jan-molak** [comment]
Thanks @fredrikand, that's a good idea. I've promoted it to [the backlog](https://waffle.io/jan-molak/jenkins-build-monitor-plugin).
