### ISSUE TITLE
Hide build meta data when it too small to be readable

### ISSUE THREAD

**Issue by davidparsson** [jan-molak/jenkins-build-monitor-plugin#190]
With the automatic font size adjustment introduced in #165, the build meta data (culprits, failure reason, ...) quickly becomes too small to be readable. With the default text scale and 4 rows of jobs, it is 6px. When adding more rows, the build number and completion time also becomes unreadable.

In these cases it would be better to hide the unreadable text entirely to save screen space.

**Comment by soeren-lubitz** [comment]
same here... please fix this soon.

**Comment by jan-molak** [comment]
Thanks for the feedback, I'm planning to address it this week.

**Comment by soeren-lubitz** [comment]
Also with this Update our Build Monitor that is run with a Raspberry Pi and a Chrome Browser overlays the progress over the job title, which makes the monitor unusable.

(see https://www.evernote.com/l/AH3QO7H_DV9E3oagQTs69u3W25g1bLTEwlQ)

**Comment by jan-molak** [comment]
Thanks @soeren-lubitz, would you mind raising a separate ticket for the Chromium issue please?

**Comment by rosstracy** [comment]
Same here,  Showing almost 30 jobs across 2 tabs, but the culprits info is unreadable, regardless of columns and font size that we set.  With the job names also recursing folder names, it becomes a catch-22 for resizing.

**Comment by jan-molak** [comment]
The issue should be fixed in the [latest build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/lastSuccessfulBuild/artifact/target/build-monitor-plugin.hpi). Please have a look and let me know your thoughts!

The text proportions might still require more tweaking, so I'm looking forward to your feedback guys :smile: 

Best,
Jan

**Comment by jan-molak** [comment]
And to address your point @davidparsson, what I think we could do is to have a "detail level" configuration setting - if set to "low" only the job name would be displayed, "medium" - job name + build number/time, "high" - job name, build number and time, culprits, identified failures, claimants etc.
Thoughts?

**Comment by davidparsson** [comment]
@jan-molak, that might do it, but I would _strongly_ prefer if the detail level could change automatically based on the number of jobs (or similar), and I'll explain why. One could for example allow the user to configure the number of jobs/rows when all details should be visible/hidden.

We use the View Job Filters plugin to configure the jobs four our build monitor views, and it's configured to display all jobs when everything is green/stable. It's often about 25 jobs but sometimes about 50. When jobs are building or failing, we only display those jobs, to highlight the important details.

What I've hoped to achieve with all of my feature requests related to "automatic scaling" is a way to at least display the job names on the screen when all jobs are visible, and when a few builds are failing, show all details using a large font size so that it's readable from a distance.

**Comment by jan-molak** [comment]
@davidparsson gotcha. So we'd have "low/medium/high/auto"? Sounds like a good idea.
Would you mind raising a ticket for that? That would be of great help, thanks!

J

**Comment by davidparsson** [comment]
@jan-molak, sure! See #194.
