### ISSUE TITLE
Chromium 22 on Raspberry Pi: Progress bar overlays the project name

### ISSUE THREAD

**Issue by jan-molak** [jan-molak/jenkins-build-monitor-plugin#192]
Raised by @soeren-lubitz in #190:

-------------------------------------

> [...] Build Monitor that is run with a Raspberry Pi and a Chromium Browser (Version 22.0.1.229.94 
> Built on Debian 7.0, running Debian 7.8 ) overlays the progress [bar] over the job title
> (see https://www.evernote.com/l/AH3QO7H_DV9E3oagQTs69u3W25g1bLTEwlQ)

![skitch](https://cloud.githubusercontent.com/assets/1089173/12245921/69676554-b8a3-11e5-9729-f6c6d97a89e1.jpg)

--------------------------------------

**Notes:**
* https://developers.google.com/web/updates/2012/09/Stacking-Changes-Coming-to-position-fixed-elements
* http://stackoverflow.com/questions/13019155/z-index-chrome-bug

**Comment by jan-molak** [comment]
@soeren-lubitz, The issue you noticed should be fixed in the [latest build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/lastSuccessfulBuild/artifact/target/build-monitor-plugin.hpi). Please have a look and let me know your thoughts!

Best,
Jan

**Comment by soeren-lubitz** [comment]
Thank you for the quick fix... we will install the latest build and let you know if it fixes our issues.

**Comment by jan-molak** [comment]
Excellent, looking forward to hearing from you.

J

**Comment by juwi** [comment]
Hi, 
just wanted to let you know, that the quick fix works. 
Thanks!

**Comment by jan-molak** [comment]
Awesome, thanks for letting me know :-)

**Comment by soeren-lubitz** [comment]
thanks @juwi
