### ISSUE TITLE
Ability to change the default settings

### ISSUE THREAD

**Issue by ipsi** [jan-molak/jenkins-build-monitor-plugin#195]
We're using this page in a screensaver, and therefore we don't have the ability to click on the cogwheel icon to change how the page is displayed (all we can do is log in via basic auth).

As such, it would be incredibly handy if we could change the default settings through the frontend somehow, so that our screensaver could use those instead of the current defaults.

**Comment by jan-molak** [comment]
Haha, that's a cool idea! :smile:
Would the approach described in #54 solve the problem?

**Comment by ipsi** [comment]
Yep, that would solve it too, and probably in a slightly better fashion.

**Comment by jan-molak** [comment]
Cool, cheers. I'll close this ticket then and if you could +1 #54 that would be great, thanks!
