### ISSUE TITLE
Can't display 7 jobs on 7 columns

### ISSUE THREAD

**Issue by Saucistophe** [jan-molak/jenkins-build-monitor-plugin#196]
It may be a minor detail, but we here at work we have 7 jobs per branch, and 1-N active branches.
Thus, I'd like to have one row per branch, and one job per column, thus 7 columns.

For now, there's only one active branch, so there's only 7 jobs; switching from 6 to 7 columns stretches the job on two rows (cf. screenshots).

![6 columns](https://cloud.githubusercontent.com/assets/7082839/12416481/f8bdab24-bea1-11e5-9e18-d0547fab2aea.png)
![7 columns](https://cloud.githubusercontent.com/assets/7082839/12416482/f8be4048-bea1-11e5-8a79-98346f4ac2db.png)

Maybe it's because the minimum font is to big to accommodate them all?

**Comment by Saucistophe** [comment]
FYI, I use the 1.8+build.201601112328 plugin version, latest Jenkins (1.644), the browser is an up-to-date Chromium.

**Comment by jan-molak** [comment]
Gotcha, what screen resolution do you use?

**Comment by Saucistophe** [comment]
1920*1200. I've stripped the Chrome tab bar, URL bar and bookmarks.
Anyway, resizing my window yields inconsistent results; sometimes 6 of them fit on the top row, sometimes only 4. I'll probably check your layout algorithm, it's intriguing!

**Comment by jan-molak** [comment]
Please do! It's a first draft so will definitely need tweaking; PRs are much appreciated ;-)
