### ISSUE TITLE
Show time since last build instead of build time

### ISSUE THREAD

**Issue by andersbbeck** [jan-molak/jenkins-build-monitor-plugin#20]
Hi,
I love this view and are currently using it on a large monitor in our development offices.

For us, the duration of each build is not that important, but I (and my coworkers) would like to monitor the activity on each project. Could it be configurable if the time shown in the right corner should be time elapsed time of build or time since last build?

That would be awesome!

**Comment by jan-molak** [comment]
[1.6 build 140](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases/tag/v1.6%2Bbuild.140) introduced this feature :smiley: Thanks for your feedback guys!

**Comment by kugel-** [comment]
Is there any way to get the duration displayed as well? For me this change is clearly a regression.
