### ISSUE TITLE
Build monitor web page becomes unresponsive

### ISSUE THREAD

**Issue by jiopaley** [jan-molak/jenkins-build-monitor-plugin#200]
We constantly see messages in the lower left portion of the webpage which indicate the build monitor web page is attempting to connect to google analytics and/or github. After a few hours, the display becomes unresponsive and no longer reflects the jenkins build view. In our environment, the PCs hosting the build monitor views are unable to connect to the internet and it is my guess is that it is these external connections which eventually cause the build monitor web page to either crash or become unresponsive. I have tried deselecting the Jenkins Build Monitor config option "Help make Build Monitor Better".

Build monitor version: 1.8+build.201601112328
Firefox for our browser

**Comment by jan-molak** [comment]
Hey @jiopaley and thanks for your feedback. Did disabling the anonymous analytics help?

**Comment by jiopaley** [comment]
Hi @jan-molak, thanks for your response. All I can find is the "Help make Build Monitor Better" tick box in the Configure System page in Jenkins. De-selecting this does not seem to fix the issue.

**Comment by jan-molak** [comment]
I see, thanks for reporting this. I'll try to reproduce the issue and will get back to you.
How many jobs do you have displayed on that screen?

**Comment by jiopaley** [comment]
I have 2 windows PCs showing the build monitor view. The first PC is displaying 12 jobs and 16 jobs on the other. Both show symptoms. It can take a few hours/overnight before the web page actually becomes unresponsive.
