### ISSUE TITLE
​Option to show the name of committer who fixed a build.

### ISSUE THREAD

**Issue by yveshanoulle** [jan-molak/jenkins-build-monitor-plugin#202]
Showing the name of the person who "probably" broke the build is very handy yet negative. Doing the same for the person who fixed the build is giving a positive credit.

**Comment by jan-molak** [comment]
Very good point, I like it!

I'll add it to the [backlog](https://waffle.io/jan-molak/jenkins-build-monitor-plugin). PRs are much appreciated too :-)

**Comment by ChadiEM** [comment]
#250
