### ISSUE TITLE
Add option to hide committers since first failure

### ISSUE THREAD

**Issue by Mathiasdm** [jan-molak/jenkins-build-monitor-plugin#203]
We sometimes have a very large amount of code coming in, with a lot of different committers. This makes a job very stretched out, so we can't get all our jobs on one screen anymore.

It would be nice to be able to disable displaying the commiters.

**Comment by jan-molak** [comment]
Hey @Mathiasdm and thanks for your feedback. Out of curiosity, how many committers could a build have in your case?

**Comment by Mathiasdm** [comment]
It's possible for us to have 50 committers (though usually it's lower).

**Comment by Mathiasdm** [comment]
We are using 1.8+build.201601112328.

**Comment by jan-molak** [comment]
Done as part of #243. A new build will be available in the Update Centre within the next couple of days, but you can always grab the latest `build-monitor.hpi` from [the CI server](http://bit.ly/SmartCodeOSCI) 😃
