### ISSUE TITLE
Option to add description under job title

### ISSUE THREAD

**Issue by naggie** [jan-molak/jenkins-build-monitor-plugin#207]
Visitors often see the dashboard and ask what each project is. As Jenkins does not support spaces in project names, it's necessary to elaborate in the description.

Just a small area for the job description under the title would be nice.

Thanks for the awesome plugin.

**Comment by jan-molak** [comment]
Hey @naggie and thanks for your feedback! It's great to hear that you're finding Build Monitor useful :-)

Jenkins does support spaces in project names, they're represented as `%20` in the project URL.
Having said that, I like the idea of displaying the project description so will add this to the backlog. 

In the meantime - remember that you can always set the project "Display Name" to something more descriptive than the project name and Build Monitor will pick that up instead. 
You can configure the "Display Name" under "Advanced Project Options" on the project configuration page.

**Comment by naggie** [comment]
> Jenkins does support spaces in project names, they're represented as %20 in the project URL.

Hm, ok I assumed it didn't as I couldn't build with spaces. It might be my code then.

> In the meantime - remember that you can always set the project "Display Name" to something more descriptive than the project name and Build Monitor will pick that up instead. 

Excellent, didn't know that was possible. Thanks!

**Comment by jan-molak** [comment]
No worries, my pleasure!
