### ISSUE TITLE
how to Displays the names of people who might be responsible for "breaking the build"

### ISSUE THREAD

**Issue by shd503** [jan-molak/jenkins-build-monitor-plugin#209]
this plugin has the functionality :Displays the names of people who might be responsible for "breaking the build" 
how to config and display

**Comment by jan-molak** [comment]
Hey @shd503 In order for the Build Monitor to display the potential culprits your project needs to be configured to use a version control system, such as git or svn. When the code change is pushed and the build that's consequently triggered fails, Build Monitor should display the "potential culprits" automatically.

Hope this helps!
Jan

**Comment by patrykperduta** [comment]
@jan-molak, and how can we turn off display of the "potential culprits"?
I can't see option for that in latest release!
