### ISSUE TITLE
Option to turn off display of potelntial culprits went gone

### ISSUE THREAD

**Issue by patrykperduta** [jan-molak/jenkins-build-monitor-plugin#213]
Is this possible to turn off display of the "potential culprits"? In [this version](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases?after=v1.6%2Bbuild.149) of jenkins-build-monitor-plugin it was possible, but I can't see this option for that in latest release!

**Comment by jan-molak** [comment]
Closing this ticket as there's #243 addressing this request.
