### ISSUE TITLE
Fit to screen option

### ISSUE THREAD

**Issue by leemarmara** [jan-molak/jenkins-build-monitor-plugin#214]
We use the plug in on a large monitor in the office to show the build status.  Since we moved to the most recent version we only get some of our jobs displayed and a scrollbar on the right.

Whilst we have changed font sizes and added columns to manually fit to the screen we can still get issues if the number of jobs displayed on the board changes (we have some jobs that only appear if they have failed).

It would be good if there was a 'fit to screen' option that ensured that all displayed jobs fitted without the need for a vertical scrollbar.

**Comment by jan-molak** [comment]
Hey @leemarmara and thanks for your feedback.

The 'fit to screen' functionality is a bit experimental at the moment and I'm continuously working on improving it.

Could you please let me know:
- how many jobs do you display on one build monitor
- the resolution of your screen
- also a screenshot would be really helpful :-)

All the best,
Jan

**Comment by leemarmara** [comment]
Hi

Thanks for getting back to me so quickly.

We currently display between 6 and 10 builds (some builds only appear on
the display if they fail).
The resolution is 1920x1080

I will try and get you some shots with the minimum and maximum builds on
them.  I'll have to take a picture rather than get an actual screenshot.

**Comment by jan-molak** [comment]
No worries :) Looking forward to seeing the screenshots!

Best,
Jan

**Comment by leemarmara** [comment]
Hi Jan

You won't believe this.  I went to get the screenshots and suddenly the fit
to screen appears to be all working.  Sorry for the waste of time.  I'll
grab a picture if it fails again.

Keep up the good work

Lee

**Comment by jan-molak** [comment]
No worries, thanks for letting me know! Automating the font scaling is a tricky thing to do, so please do let me know if you spot any issues :-)

By the way, I've improved the font scaling algorithm a bit in the latest build. If you'd like to play with it before it hits the Jenkins Update Centre and let me know what you think you can [find it here](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/36/artifact/build-monitor-plugin/target/build-monitor-plugin.hpi).

All the best,
Jan
