### ISSUE TITLE
Settings-Dialog: Slider Interaction with Clicking

### ISSUE THREAD

**Issue by TomNextSense** [jan-molak/jenkins-build-monitor-plugin#217]
As a user I want to be able to adjust the text scale (and probably also the number of columns) using click events on the slider bar (including the vertical space around the visual line) - additionally to dragging the dot.

Background: We are using a Smart-TV as build monitor. The browser is capable of rendering the build monitor page, but the automated scaling fails. We would need to adjust the text scale. But the remote of the TV only can create click-, but no drag-events. To be able to click also some pixels above the line (where the numbers are displayed) would help too, as positioning the mouse withe remote is quite tricky. Thanks a lot in advance!

Screenshot of current usage: ![img_2095](https://cloud.githubusercontent.com/assets/19219939/15069225/8a4897fa-137c-11e6-998a-d933dc27ce68.JPG)

**Comment by jan-molak** [comment]
Hey @TomNextSense and thanks for the suggestion! Slider seemed like a good idea at a time, but it's proven a bit problematic and maybe not necessarily the best user experience.

I'm was actually thinking of replacing it with two buttons and a text field showing the current value, so something like that:
`[ - ] [ 7 ] [ + ]`

Would that work better in your case?

Best,
Jan

**Comment by TomNextSense** [comment]
Hello @jan-molak ,
thank you for your fast response. Anything that can (also) be operated using click events and where the corresponding UI element is not too tiny would be good for us.
(So if the [ + ] [ - ] Buttons are at least the size of the done buttons height, it should be good.
Regarding slider: Yes, also on our Pi the slider is difficult to operate as the JS-performance of the browser on the Pi is really bad. There the "button solution" would help too.)
Best regards
    Tom

**Comment by TomNextSense** [comment]
Another idea that just came up in a discussion with my colleagues: Would it be possible to allow configuration of the "local parameters" (like number of columns and font size) via get parameters? This would make it unnecessary to rely on the onscreen settings dialog. :+1:

**Comment by jan-molak** [comment]
Sure, that makes sense as well, there's actually a ticket raised for that: #54 (and pull requests are also welcome! ;-) )
