### ISSUE TITLE
Different color for aborted builds

### ISSUE THREAD

**Issue by gozdal** [jan-molak/jenkins-build-monitor-plugin#218]
If you abort a build, the color displayed is the same as a failed build.
I'd be great if the color was different together with information who aborted a build.

**Comment by aliciabauman** [comment]
+1 for this, this is an issue that I get asked about by my team almost daily.

**Comment by jan-molak** [comment]
Fair enough :-) My only reservation is that disabled builds are displayed as grey. We could make aborted builds grey and disabled ones ..... uhm, maybe the colour of the last build, but dimmed? or dark grey?

Thoughts?

**Comment by gozdal** [comment]
@jan-molak brown maybe? gray for disabled, yellow for unstable, red for failed, gray for disabled and brown for aborted. Striped for claimed. Any more colors needed?

**Comment by aliciabauman** [comment]
I like the idea of making aborted builds grey and disabled ones a dimmed color that represents the previous build's success/failure! Maybe also add a note that says disabled.
