### ISSUE TITLE
Version control descriptions

### ISSUE THREAD

**Issue by Elvaron** [jan-molak/jenkins-build-monitor-plugin#222]
It would be great if we had some options to set a description under the job name based on SCM.
For example, the current/most recent git branch or SVN revision or such.

As an alternative, if the plugin rendered a per-job environment variable or such that can be set through the build itself, we could completely customize the description.

**Comment by Elvaron** [comment]
Almost perfect. Repeated use of task doesn't produce new line :smile: 
Thanks a lot for working on this :+1: 

![builddescription](https://cloud.githubusercontent.com/assets/2558087/15851102/b325bad0-2c9b-11e6-8c1d-961adb17e8f4.png)

**Comment by jan-molak** [comment]
Haha, cool, thanks for your feedback! 😄 What's the configuration of your build description setter for the "Release Pipeline" job?

**Comment by Elvaron** [comment]
The first one sets it to _${BuildBranch}_, i.e. the git branch used for the build. Our version number scheme is MajorProductVersion.MinorProductVersion.WebUpdateVersion.JenkinsBuildNumber, so the branches only have 3 numbers.

After one of the initial tasks has run through, the fourth number has been determined, written to a props file, environment injected into the _${FinalBuild}_ variable. And thus, the second execution of the **set build description** task sets the description to (or, apparently, appends) _${FinalBuild}_, letting us know of the resulting release candidate number.

**Comment by jan-molak** [comment]
495d38f should do the trick.

The new build will be available in the Update Centre within the next couple of days, but if you'd like to try it out now you can always grab the latest from [the CI server](https://bit.ly/SmartCodeOSCI)!

Best,
Jan
