### ISSUE TITLE
Color-blind-mode: Displays not always the right background

### ISSUE THREAD

**Issue by Luke081515** [jan-molak/jenkins-build-monitor-plugin#224]
* Create a build
* Fail the build once
* Run the build now:
The field is now blinking, and it is red, but there is not the right color at the backgroud which a not blinking red field has.

**Comment by jan-molak** [comment]
Hey @Luke081515, thanks for pointing this out! The latest build should resolve the problem. Looking forward to hearing your thoughts.

Best,
Jan

**Comment by Luke081515** [comment]
@jan-molak I checked it out, it works now as expected. Thank you for your fix.
Best,
Luke

**Comment by jan-molak** [comment]
Perfect, thanks for your help! 😄
