### ISSUE TITLE
How to customize theme

### ISSUE THREAD

**Issue by Alexhha** [jan-molak/jenkins-build-monitor-plugin#226]
Hello is it possible to change color for build number? I have tried add the following code

```
span.ng-binding {
   color: yellow;
}
```

but in the [result ](http://i.imgur.com/whV4KYS.png) I got not what I expected

How can I make build name more yellow?

Thanks in advance

**Comment by jan-molak** [comment]
Hey @Alexhha,

Changing some of [the stylesheets](https://github.com/jan-molak/jenkins-build-monitor-plugin/tree/fe8e0c0bc2cf5a8a1a6fc1575825650c45c89098/build-monitor-plugin/src/main/webapp/less) and [rebuilding the plugin](https://github.com/jan-molak/jenkins-build-monitor-plugin/wiki/Development-Guide) should be enough.

Having said that, `ng-binding` is probably not what you were looking for.
It's an [internal class](http://stackoverflow.com/questions/20831804/what-does-ng-binding-mean-in-angular) used by [Angular](https://angularjs.org/), a JavaScript framework Build Monitor uses.

Hope this helps!
Jan
