### ISSUE TITLE
Persist UI configuration

### ISSUE THREAD

**Issue by xam7247** [jan-molak/jenkins-build-monitor-plugin#227]
Jan, its really a great plugin to simplify workflow view. 

It would really help if we could persist the UI configuration (say: a default configuration), which shows up consistently same on all machines, and if user needs a custom one he can override it for a particular screen. Currently since this is stored in cookies, each member in the team needs to adjust their views + each time we clear cookies, its all reset.
##

**Comment by jgrant216** [comment]
I've been using this plugin in "My Views" for quite a while, but finally created a view for everyone to use.  I was surprised that they did not get the same view configuration (columns/text size) as I had set.

Definitely interested in a default either at the job level or, worst case, global Jenkins configuration level as asking everyone to set these will reduce the likelihood of their using the view.

Thank you in advance!

**Comment by jan-molak** [comment]
Hey guys and thanks for your great feedback and ideas! I'm currently contemplating taking one of the below approaches:
- adding an option to "propagate the current configuration to all displays", and persisting it on Jenkins
- adding an option to "generate a URL" that contains the configuration as URL parameters

I'm leaning more towards the second option as it, opposed to the first one, can't lead to a "configuration war" where dozens of developers try to persist their changes, overwriting everybody else's 😉 
Also persisting the configuration in the URL would help to support unattended displays (#54).

Thoughts?

**Comment by jgrant216** [comment]
Unfortunately, a link will not work for those of us switching to this view from another view using either the tabbed or dropdown list of views.  Your proposed solution would work for those entering the view via a link.

I still prefer the a shared configuration either defined at the view configuration level or even at the Global Jenkins configuration level.  Of course, the Global Configuration level would result in all Build Monitor views having the same initial setting... which they already do.

As the current default is severely too small (unreadable) for our use, other members of the team opened it once and abandoned it immediately even though I had explained how to configure it.  This is unfortunate.

**Comment by jan-molak** [comment]
@jgrant216 - I'm sorry to hear that; Which version of Build Monitor are you guys using?

**Comment by jgrant216** [comment]
We upgrade all plugins monthly, so we are not very far behind at this point.  Our current version is 1.9+build.201605021413 and I see there is a new version available, 1.9+build.201606131328, which we will be installing in the next week or so.

Some of our job names are quite lengthy, so maybe some scaling is being applied as a result of that.

As you mentioned, the initial font size was adjusted in a prior release.  I am suggesting you expose that at least at the global Jenkins Configuration level for administrators to adjust if necessary.

**Comment by jsframe** [comment]
We just upgraded from an older version of jenkins to the latest (v2.20) and found that the default font size in the build monitor view is now too small, and so when viewing it on our shared monitors  - the font is unreadable.  Updating the settings on these shared monitors is difficult and they do not remember them.

So we definitely would benefit greatly from this enhancement.

**Comment by jan-molak** [comment]
Thanks @jsframe, probably Jenkins broke backwards compatibility again... I'll prioritise this ticket in the backlog, but I'm under heavy load with other projects at the moment, so if someone raised a pull request that would speed things up!

**Comment by gabel** [comment]
Any news on it? Due to this issue we cannot use it on floor monitors.

**Comment by jan-molak** [comment]
@gabel - sorry, I didn't have a chance to look into this yet. Pull requests are welcome though!
