### ISSUE TITLE
Build Monitor eats CPU

### ISSUE THREAD

**Issue by akaihola** [jan-molak/jenkins-build-monitor-plugin#230]
I have a dashboard of 44 build jobs which I like to keep open in Firefox. Unfortunately this really eats my laptop battery.

Using the new `about:performance` analyzer in Firefox 47, I can see that it's indeed the Build Monitor tab which is consuming cycles:
```
Impact on framerate: 9/10.
CPU usage: 85%.
System usage: 6%.
Blocking process calls: 0%.
Measure start: 89 seconds ago.
Processes: 4918 (parent)
```

**Comment by jan-molak** [comment]
Thanks @akaihola, it could be the `ng-repeat` directive. I'll look into that when I have a moment (PRs welcome of course!!)
