### ISSUE TITLE
Support rendering of HTML in "description" field

### ISSUE THREAD

**Issue by Pefou-flo** [jan-molak/jenkins-build-monitor-plugin#238]
Hello,

Since the last version of build-monitor, job descriptions were added but in our jenkins instance, job descriptions contains url link to sonar/bitbucket and this isn't properly showed

Would it be possible for this to display only the text or even add an option to hide the description if we don't want it ?

![build-description](https://cloud.githubusercontent.com/assets/16313165/16225600/b6079f90-37a7-11e6-9b06-af877874dcc9.png)
![build-monitor-bug](https://cloud.githubusercontent.com/assets/16313165/16225601/b608aeda-37a7-11e6-8599-e6ec27c28d7c.png)

**Comment by jan-molak** [comment]
Hey @Pefou-flo and thanks for your feedback! 

It looks like in the light of your request, as well as #241 it probably makes sense to:
- add an option to hide the descriptions, so people can disable them if they don't need them
- allow the descriptions to render html content unescaped if people like to use it this way, but to avoid potential XSS vulnerabilities, also:
  - and a global config option to either allow or disallow rendering the html

Thoughts?

**Comment by Pefou-flo** [comment]
Hey,

Both your ideas sounds awesome :) I did take some time to clone your repo but as of now I didn't have time to try & make an option to disable descriptions so I've revert back to the previous version.

I guess due to xss vulnerabilities, it would be good to at least add the option to allow or disable description (without any html rendering); but if you manage to find enough time to do all your points, that would really be good !

Anyhow, great add-on, would love to see this implemented in order to be able to upgrade it again :D

**Comment by jan-molak** [comment]
495d38f should do the trick.

The new build will be available in the Update Centre within the next couple of days, but if you'd like to try it out now you can always grab the latest from [the CI server](https://bit.ly/SmartCodeOSCI)!

Best,
Jan

**Comment by vladichko** [comment]
jan-molak, i am confused, is 495d38f supposed to solve "Hide job description" #241 ? 
i also have a lot of text in description.

**Comment by jan-molak** [comment]
Hey @vladichko, that commit was there to allow for the links to be displayed.

**Comment by vladichko** [comment]
So it appears that "Hide job description" #241 is closed but not solved... right? It seems that I have no permissions to reopen it, can you please help/advise?

**Comment by MadhavGitlab** [comment]
Any update on "Hide job description" feature?

**Comment by nofacer** [comment]
Any update on "Hide job description" feature?

**Comment by nofacer** [comment]
a workaround is to overwrite the css

```
.build-monitor .widget.basic.project header ul.details{
  display: none;
}
```
