### ISSUE TITLE
Play sound on build failure

### ISSUE THREAD

**Issue by ghost** [jan-molak/jenkins-build-monitor-plugin#24]
I'm after a way to draw attention to the build monitor on a failed build and playing a sound would seem to do that.  Could this plugin be extended to play a sound on failures - really a duplication of the functionality of the Jenkins Sounds plugin but I cannot figure out how to get that working on the PC the build monitor is running on.

**Comment by taylormathewson** [comment]
There's a plugin https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Sounds+plugin that supports playing sounds on webpages, might be easier to integrate that.
