### ISSUE TITLE
Hide job description

### ISSUE THREAD

**Issue by theproshin** [jan-molak/jenkins-build-monitor-plugin#241]
Нi!
Help me, please.
How hide description?
Jobs very many. All dont't show on display.

![image](https://cloud.githubusercontent.com/assets/5551744/16523177/a71813f6-3faa-11e6-9bd3-9d0d765b17b3.png)

**Comment by jan-molak** [comment]
Oh boy! I've never expected job descriptions to have so much stuff in them!! :-) Fair enough and thanks for your feedback. I should be able to look into this over the next two weeks, in the meantime - pull requests are welcome.

Jan

**Comment by jan-molak** [comment]
Closing so that we can track it as #238

**Comment by amollberg** [comment]
This issue is NOT solved with #238 because it is till not possible to hide the job description. HTML support in this plugin does not help because Jenkins can wipe e.g. `style="display:none"` before this plugin sees it. Please reopen this. or advice a workaround.
