### ISSUE TITLE
Display Code Styling and Unit Test Status as a Badge in each block

### ISSUE THREAD

**Issue by chenfli** [jan-molak/jenkins-build-monitor-plugin#242]
Hi @jan-molak,
I love the dashboard, and I am checking the new Unit Test Status feature you added (#148, #170, #228).

I am looking for code styling as well.

As I see it, is that you will have some minimized Graphs (as you have on the Job Page), with the code style and the Unit Tests.

Is this possible,

Thanks
Chen
##

**Comment by jan-molak** [comment]
Hey @chenfli and thanks for your kind words :-) 

I think that some minimalistic sparklines could definitely be useful! Pull requests welcome!

J

**Comment by jan-molak** [comment]
Hey @chenfli, this should be doable now that the Build Monitor [supports badges](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases/tag/v1.11%2Bbuild.201701152243) #267.
Please check the release notes as they describe the solution to your first example. Displaying the number of code style violations would be quite similar too.

Granted, the badges don't support the sparklines yet, but hey, one step at a time ;-)

Hope this helps,
Jan
