### ISSUE TITLE
Question: Does the build monitor plugin visually mark claimed failed tests by default when the claim plugin is activated?

### ISSUE THREAD

**Issue by KasperJanssens** [jan-molak/jenkins-build-monitor-plugin#244]
We make the difference between 'red' builds an 'yellow' builds. Red builds can be claimed with one click and the plugin indicates this visually by striping the build in different reds. Yellow builds need to get all their tests claimed separately it seems, and the build monitor doesn't seem to indicate anything. I don't seem to find any option or switch, am I missing something? Old version of the plugin though, 2.3, but not my server so I can't just upgrade without good reason.

**Comment by jan-molak** [comment]
Hey @KasperJanssens, 

Yes, as long as Jenkins thinks that the build is claimed, Build Monitor will indicate that.

However, on top of having the Claim Plugin installed, you also need to enable a "Post-build action" on each Jenkins job to "Allow broken build claiming".

<img width="1033" alt="screen shot 2016-07-05 at 23 58 45" src="https://cloud.githubusercontent.com/assets/1089173/16602523/c269538a-430c-11e6-8c8a-9df0a3ea9011.png">


The above screenshot comes from Build Monitor [acceptance tests](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/Serenity/index.html) verifying this behaviour, so have a look at the "[Claiming a broken build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/Serenity/593f4b698486f6359ff007b3eade2f550005e9a4c5b027fb5e65e1ad184a43ba.html)" scenario for step-by-step instructions.

Hope this helps!
Jan

**Comment by KasperJanssens** [comment]
Hey Jan, thinks for the fast response.  Thing is, this seems to work for 'red' builds but not for 'yellow' ones. It might be a bit debatable whether we use those colour codes correctly or not, but can you confirm  that this should also work for the 'yellow' builds? The example in step by step instructions also seems to work for 'red' builds (the screenshots do, anyway :-)).

**Comment by KasperJanssens** [comment]
@jan-molak , just a small update, the problem seemed to be caused by the fact that we configured the 'Allow build claiming' BEFORE we configured the junit test report publishing. If we configure the order correctly on jenkins then it all works like it should. Something that wasn't very clear to me.

**Comment by jan-molak** [comment]
@KasperJanssens, ah interesting! Many thanks for the update!

Yes, the build must be recognised as failing by JUnit (or any other plugin that sets the build result to `failure`) before the Claim plugin can mark it as claimable.

Glad you got it resolved!
