### ISSUE TITLE
Configurable Job Names

### ISSUE THREAD

**Issue by george-nelson** [jan-molak/jenkins-build-monitor-plugin#248]
**Feature request**: Is there a way to use a use a different name instead of the the job name ?

e.g. if the actual job name is _MyAwesomeVeryLongAPITest_, I want would to change that name to _MyAPITest_ only in dashboard.

Thanks

**Comment by jan-molak** [comment]
Hey @george-nelson, Jenkins supports custom job names so if you set one, Build Monitor will pick it up.

To change the display name go to the configuration page of your Jenkins job and scroll down to the "Advanced Project Settings" section:
<img width="1147" alt="screen shot 2016-07-20 at 21 12 16" src="https://cloud.githubusercontent.com/assets/1089173/17001462/030969e4-4ebf-11e6-837e-ed436f9abe56.png">

After clicking on the "Advanced" button, a menu will appear where you can specify a custom "Display Name":
<img width="1144" alt="screen shot 2016-07-20 at 21 12 30" src="https://cloud.githubusercontent.com/assets/1089173/17001486/1aacc690-4ebf-11e6-8914-9e43ff4aa3ba.png">

Let me know if it worked for you!

All the best,
Jan
