### ISSUE TITLE
Option to display code coverage number

### ISSUE THREAD

**Issue by Shmigget** [jan-molak/jenkins-build-monitor-plugin#258]
Enhancement -- Would be great to have code coverage percentages displayed (via JaCoCo or Emma) to foster competition among the development teams to get their respective numbers higher.  
##

**Comment by jan-molak** [comment]
Hey @Shmigget, that should be doable now that the Build Monitor [supports badges](https://github.com/jan-molak/jenkins-build-monitor-plugin/releases/tag/v1.11%2Bbuild.201701152243) #267.

In your post-build groovy script you could:
- Retrieve the [`JacocoBuildAction`](https://github.com/jenkinsci/jacoco-plugin/blob/master/src/main/java/hudson/plugins/jacoco/JacocoBuildAction.java) from the build
- Retrieve the value of line coverage - `getLineCoverage`
- Assign it to a badge

Hope this helps!
Jan
