### ISSUE TITLE
Multiple Theme Choices.

### ISSUE THREAD

**Issue by christoff-1992** [jan-molak/jenkins-build-monitor-plugin#262]
Thanks for such an awesome tool.

Wondering has anyone else created a theme for build monitor, or are there others available?

If not I may fork the repo and take a look myself, possibly submitting a pull request if all goes to plan.

Thanks

**Comment by jan-molak** [comment]
Thanks for your kind words, I'm glad that you find it useful :-)

I'm not sure if anyone has created any alternative themes, but if you'd like to create one I'd be more than happy to review it and merge it in. Most of the machinery is there already (like LESS support for instance), so it shouldn't be too difficult to achieve.

There was a suggestion (#135) to allow Build Monitor to specify local CSS overrides, but I'm not convinced  and would much rather see alternative themes people could switch between without having to hack CSS together in a form field.

Best,
Jan
