### ISSUE TITLE
Correct build status for External Job projects

### ISSUE THREAD

**Issue by hschink** [jan-molak/jenkins-build-monitor-plugin#265]
Hello @jan-molak! Thanks a lot for this great plug-in! The only thing I miss at the moment is that the build monitor shows the build status for external jobs (``hudson.model.ExternalJob``) correctly. Currently, external jobs are always considered disabled by the build monitor. However, external jobs are by default disabled because external jobs do not have any build logic and, consequently, ``hudson.model.ExternalJob``'s superclass [``hudson.model.ViewJob`` always returns ``false`` for ``isBuildable()``](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/ViewJob.java#L92-L94).

Maybe extending [``isDisabled()`` in ``JobView``](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/master/build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/JobView.java#L88-L90) by something like the following
```Java
return ! (job.isBuildable() || job instanceof hudson.model.ViewJob);
```
could do the trick? What do you think?

Thanks a lot for your help!

**Comment by jan-molak** [comment]
Hello @hschink! Thanks, I'm glad that you're finding it useful 👍 

Sure, I don't really use external jobs, but if you'd like to propose a PR I'd be happy to merge it in? (It's a one-liner plus tests, and you'd be listed as a [contributor](https://github.com/jan-molak/jenkins-build-monitor-plugin/graphs/contributors) ;-) )

Maybe something along those lines, so that we remember that `ViewJob` represents an external job:

```java
return ! isEnabled(job) || isExternal(job));
```
(some private helper methods to encapsulate the logic and make it a bit more obvious).

Looking forward to hearing from you!
Jan

**Comment by hschink** [comment]
Hello @jan-molak! Ok, let me try to get into it. However, don't expect an proposal by next week. :wink:

**Comment by hschink** [comment]
Hello @jan-molak! I prepared PR #266 for this issue. May you have time to look into it?

Looking forward to your comments!
Hagen

**Comment by jan-molak** [comment]
Hello @hschink, sure, apologies, I was off the grid for two weeks. I'll check it out now.

Best,
Jan

**Comment by jan-molak** [comment]
Thanks for your contribution, @hschink. The PR looks good to me, merged! 

I've also added [acceptance tests](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/master/build-monitor-acceptance/src/test/java/features/ShouldSupportExternalProjects.java) to [demonstrate](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/Serenity/) the usage of this new feature.

Best,
Jan

**Comment by hschink** [comment]
Your welcome, @jan-molak! And thanks a lot for the acceptance tests. :+1:

Hagen

**Comment by jan-molak** [comment]
No problem, if you'd like to try out the latest build before it hits the Jenkins Update Centre you can [download it here](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/lastSuccessfulBuild/artifact/build-monitor-plugin/target/build-monitor-plugin.hpi).
