### ISSUE TITLE
404 on /static/xxxxx/plugin/build-monitor-plugin/themes/industrial.css

### ISSUE THREAD

**Issue by JulienBreux** [jan-molak/jenkins-build-monitor-plugin#268]
Hi,

Browser: `Any`
Version: `1.10+build.201611041949`
Jenkins Version: `2.30`

I've a 404 on `/static/xxx/plugin/build-monitor-plugin/themes/industrial.css` file.
But not on `/static/xxx/plugin/build-monitor-plugin/styles/normalize.css`.

(In page : `/view/<view-name-for-build-monitor-plugin>/`)

I've already restart Jenkins.

How can I fix this?

**Comment by jan-molak** [comment]
Hi there! Does your jenkins error log mention any build monitor-related errors or exceptions?

**Comment by yael-lorenzo-olx** [comment]
I just installed the plugin version 1.10+build.201611041949 in Jenkis 2.7.

Added two jobs and in the Chrome console I can see this

Failed to load resource: the server responded with a status of 404 (Not Found)
angular.min.js:40
http://zzzzzz.zzz.zz/plugin/build-monitor-plugin/scripts/jenkins.js
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=buildMonitor&p1=Err…Fbuild-monitor-plugin%2Fvendor%2Fangular-1.5.8%2Fangular.min.js%3A21%3A179)

The configuration button does not work either.

How can I help?

**Comment by jan-molak** [comment]
Hey guys, I just checked Build Monitor 1.10+build.201611041949 running on the latest LTS version of Jenkins - 2.19.4 and am afraid that I can't reproduce the issue.

Could you please let me know if your Jenkins instances throw any Build Monitor-related errors in the main [Jenkins log](https://wiki.jenkins-ci.org/display/JENKINS/Logging)?

**Comment by yael-lorenzo-olx** [comment]
I found the issue.

This server https://jenkins-dev.mycompay.com/view/Monitor/

references

**Comment by yael-lorenzo-olx** [comment]
Ok, we found the issue, it was a proxy configuration filtering the rule "/jenkins" and forwarding the request "/plugin/build-monitor-plugin/scripts/jenkins.js" to another IP.

**Comment by jan-molak** [comment]
Cool, glad you found the root cause! Thanks for letting me know :-)
