### ISSUE TITLE
Progress of jobs are not working in IE11/Edge

### ISSUE THREAD

**Issue by khipis** [jan-molak/jenkins-build-monitor-plugin#272]
Hi!

Progress of builds is not working on IE11/Edge webbrowser (Unfortunately we are obliged to use them on our TV for monitoring master).

We were able to fix that with this workaround:

in **controllers.js**

    directive('animateOnChange', ['$animate', '$timeout', function($animate, $timeout) {
        return function(scope, elem, attr) {
            scope.$watch(attr.animateOnChange, function(newValue, oldValue) {
                if (newValue !== oldValue) {
                    var cssClass = 'updated';

                    elem[0].style.width = newValue + '%';  //------> THIS LINE IS ADDED

                    $animate.addClass(elem, cssClass).then(function() {
                        $timeout(function() {
                            $animate.removeClass(elem, cssClass);
                        }, 5);
                    });
                }
            });
        }
    }]).

And progress starts to working on IE11/Edge.

However I'm not sure if that solution is ok to make PR from it :)

Regards

**Comment by jan-molak** [comment]
Hey @khipis, yeah, that could work, but I think the problem you're seeing has something to do with how IE interprets angular's directives - angular/angular.js#2186

I've just tweaked the implementation slightly, would you mind letting me know if the [latest build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/lastSuccessfulBuild/artifact/build-monitor-plugin/target/build-monitor-plugin.hpi) works better for you?

Thanks,
Jan

**Comment by khipis** [comment]
Yeah, thank you, I will back with feedback as soon as possible (probably end of next week) cheers

**Comment by jan-molak** [comment]
Brilliant, if it's all good for you I'll push an update.

**Comment by khipis** [comment]
Hi, sorry for late response. 
But now it's confirmed - your solution for this problem works pretty well. Progress is showing on IE11/Edge now. 

Thank you very much :+1:

**Comment by jan-molak** [comment]
Great stuff, thanks for the confirmation. I'll push the latest build to the Update Centre shortly.
