### ISSUE TITLE
Disable loading google analytics script if the user opts out from anonymous analytics

### ISSUE THREAD

**Issue by larsrh** [jan-molak/jenkins-build-monitor-plugin#274]
According to the [privacy policy](https://github.com/jan-molak/jenkins-build-monitor-plugin/wiki/Privacy-Policy) it is possible to opt-out of the data collection. I just did that, but it didn't appear to have any effect on the build monitor page.

Grepping the sources actually reveals no occurrences in the build view template; only in `global.jelly` which as I understand renders a section in the Jenkins configuration. I would expect an occurrence in `index.jelly`.

**Comment by jan-molak** [comment]
Hi @larsrh, you can opt out from the anonymous data collection in the main Jenkins settings. 
Doing so [disables google analytics](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/master/build-monitor-plugin/src/main/resources/com/smartcodeltd/jenkinsci/plugins/buildmonitor/BuildMonitorView/index.jelly#L61) as per the [google analytics manual](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out).

Is that not the behaviour you're seeing?

**Comment by larsrh** [comment]
You're right. I was puzzled why the Google Analytics script would even be loaded if data collection is disabled. Would it be possible in the template to only conditionally import the scripts? (This is relevant in situations where external scripts are prohibited company-wide.)

**Comment by jan-molak** [comment]
Sure, I don't see why not. I'd be happy to review and merge in a pull request if you'd be willing to look into this?

Just out of curiosity - could you please elaborate a bit more on your particular situation? Why would a company prohibit loading external scripts from reputable sources (such as google)? Would the same policy apply to other scripts (say angular or jQuery loaded from a CDN)?

**Comment by larsrh** [comment]
Yeah, no problem, I'll try to get onto that soon. Should be easy enough. Thanks for your consideration!

At least in Germany, many people are quite privacy-aware. In the context where our Jenkins is deployed, it's frowned upon to talk to Google or other third-party services at all if not strictly necessary. Doing so would require bureaucratic approval.

**Comment by jan-molak** [comment]
Gotcha, thanks for the clarification. I'm looking forward to the PR, thanks!

**Comment by larsrh** [comment]
I've filed a PR now with my suggested changes! Sorry for the initial confusion :smile:

**Comment by jan-molak** [comment]
No worries, thanks for the PR 👍

**Comment by Tirus42** [comment]
The issue seem to exists again. Our build monitor includes google analytics even with disabled statistic collection. Maybe a regression?

**Comment by KalleOlaviNiemitalo** [comment]
@Tirus42, did you disable the correct thing? With Build Monitor version 1.12+build.201809061734, if I uncheck "Help make Build Monitor better" in "Configure System", then the Web browser does not attempt to load `//www.google-analytics.com/analytics.js`, even if I check "Help make Jenkins better by sending anonymous usage statistics and crash reports to the Jenkins project."

The Web browser makes a request to <https://api.github.com/repos/jan-molak/jenkins-build-monitor-plugin/releases/latest?callback=angular.callbacks._0>, though. I suppose this issue does not cover that one.
