### ISSUE TITLE
Ability to hide Build Failure Analyzer output (BFA)

### ISSUE THREAD

**Issue by LinkMJB** [jan-molak/jenkins-build-monitor-plugin#275]
When BFA identified problems are revealed on the radiator view, the size of the given project status becomes unwieldy due exposure of the stack trace. Can we be given an option to filter/turn off BFA identified problem exposure on the radiator view please?

**Comment by jan-molak** [comment]
Yes, I guess a nice and long stack trace is not necessarily what you'd want to show there ;-)

Build Failure Analyzer allows people to define both the name and the description of a given failure type (as you can see in the [acceptance test here](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/Serenity/bdce7af6033f9751323fe3e1755dd257.html)); I'm just thinking what would provide the best experience - being able to choose between displaying the name or the description (Build Monitor shows the description at the moment), or disabling the thing altogether?

Thoughts?

**Comment by patrickdepinguin** [comment]
FYI, I bumped into this same thing today. We are using BFA to hook jUnit test results into build monitor. We now have a job where the 'Stack trace' is indeed filled in, and contains a build log of possibly a few hundred lines, which now shows on build monitor.

For my use case, I'd prefer to see the name of the test failures, but not the description.

I guess most flexibility will be where users can choose whether to display the name, the description, or both. 

Regarding whether this should be a cookie-based (client-based) configuration, or server-based: in my example above it's the job that determines the unusability of the description, so I would think  server-side configuration would be better. OTOH there may be cases where a specific monitor would want to be configured differently.
In fact, I think it would be great if at server-side one can configure defaults, which can also be overwritten at client-side. This is most flexible.

**Comment by patrickdepinguin** [comment]
@jan-molak Following patch covers my current use case: it uses the name instead of the description of the problem. Clearly this is a quick fix, it does not cover the configurability aspect as discussed above.

```patch
diff --git a/build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeDiagnosedForProblems.java b/build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeDiagnosedForProblems.java
index 29b0a00..1344b29 100644
--- a/build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeDiagnosedForProblems.java
+++ b/build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/CanBeDiagnosedForProblems.java
@@ -40,7 +40,7 @@ public class CanBeDiagnosedForProblems implements Feature<CanBeDiagnosedForProbl
 
         public Problems(FailureCauseBuildAction action) {
             for (FoundFailureCause failure : action.getFoundFailureCauses()) {
-                failures.add(failure.getDescription());
+                failures.add(failure.getName());
             }
         }
 
```

**Comment by jan-molak** [comment]
It seems like most people would rather see the name rather than the description of the failure displayed, so I'm happy to go with that. @patrickdepinguin - would be happy to submit your patch as a PR?
