### ISSUE TITLE
Progress animation stops at "100%" progress

### ISSUE THREAD

**Issue by dcendents** [jan-molak/jenkins-build-monitor-plugin#279]
Hi,

The progress bar animation "blinks" every time the progress % change. But once the build time exceeds the previous build, the progress bar is not animated and it is hard to distinguish these current builds from other completed builds.

I would prefer if the animation was based on the build time, which will always change every time the data is refreshed.

To give some background info, I've converted all our jobs to pipeline and our strategy to get faster results is to launch as many concurrent builds (even of the same job) as we can. They all compete for an available executor. Half-way through they will try to acquire a lock before they run their integration tests. We only want the latest build of a particular job to go through and cancel previous builds (using reverseOrder on the lock and milestone). So when the server is busy, a job can "build" for much longer than its previous build and the progress bar is set at 100% and it is not animated so we cannot easily see it. It won't even be listed in the build queue.

Thanks

**Comment by dcendents** [comment]
The following update seems to work if you find the proposal acceptable:

widgets.jelly:
```xml
        <div class="progress"
             data-ng-if="project.estimatedDuration &amp;&amp; project.progress &gt; 0"
             animate-on-change="project.lastBuild.timeElapsedSince"
             data-ng-style="{ 'width': project.progress + '%' }"
        >
            <span class="value">{{project.progress}}%</span>
        </div>
```

It will animate whenever timeElapsedSince is modified. To prevent unnecessary "hidden" animations of completed builds, the progress div is only added to the DOM when a project is building.

**Comment by jan-molak** [comment]
The bar should keep on animating when a project takes longer than expected, but I haven't used the locks and reverse order in this context, so am not sure if it would. I think adding `data-animate-on-change` sounds sensible and am happy to merge it in if it fixes the problem you're seeing.
