### ISSUE TITLE
Feature Request: Group Jobs

### ISSUE THREAD

**Issue by steven-terrana** [jan-molak/jenkins-build-monitor-plugin#281]
first off, awesome plugin. 

I think it would be great if you could group jobs and have them be displayed under a banner with the group name. 

Currently have a set up where there are 10 or so folders - each having about 3 jobs. 

While I'm getting by through displaying jobs alphabetically and then having 3 columns, I see potentially problems in achieving the look and field desired if certain folders have different numbers of jobs. 

If you have ever used Grafana, that's along the lines of what I'm thinking.  

Let me know what you think! 
Thanks,
Steven

**Comment by jan-molak** [comment]
Thanks! I'm glad that you find it useful :-)

Sure, the capability to group jobs is something that's been requested on several occasions, but other things took priority I'm afraid - #130, #206, #246

It would be great to see this idea come to fruition though, so if you'd like to propose a PR I'd be more than happy to merge it in.

Looking forward to hearing your thoughts,
Jan
