### ISSUE TITLE
Neo-light theme partly breaks build monitor style

### ISSUE THREAD

**Issue by luebbe** [jan-molak/jenkins-build-monitor-plugin#282]
In order to get a modern (read flat) looking UI for our Jenkins installation I activated the "simple theme" plugin and the neo-light stylesheet (http://jenkins-contrib-themes.github.io/jenkins-neo-theme/dist/neo-light.css).
This partly breaks the appearance of build monitor, because there's now dark gray text on green or red background, which is hardly readable. "Back in the green", "n builds have failed", "last build" time.

![screenshot](https://cloud.githubusercontent.com/assets/3872576/22013571/fbb39e4e-dc99-11e6-81c9-ecb7dd54d038.png)

**Comment by jan-molak** [comment]
Hey @luebbe and thanks for reporting this! @khipis has also reported this problem in #291 and was kind enough to fix it in #295.

A new release of Build Monitor will be available early next week, so please update your installation as soon as convenient.

Best,
Jan

**Comment by walliski** [comment]
@jan-molak 
For this specific theme we are having other problems:

Footer breaks:
![kuva](https://user-images.githubusercontent.com/5192434/26879439-c73104f8-4b99-11e7-9ffb-606afe24586b.png)

Also font size and other styling such as bold breaks.

Maybe would be a good idea to figure out how a more general way of fixing errors instead of making everything important?

**Comment by luebbe** [comment]
Am I missing something? I was hoping to see a new release of build monitor in the past months, but the latest release is still: https://github.com/jan-molak/jenkins-build-monitor-plugin/tree/v1.11%2Bbuild.201701152243
Is everything ok? Have the releases moved to a different location?

**Comment by jan-molak** [comment]
Hey @luebbe, I was hoping to get a couple more PRs merged in before the release, but it seems to take longer than expected. I've just pushed the latest build to the Jenkins Update Centre and will push the next one whenever the PRs are ready.

Hope that helps!
J

**Comment by luebbe** [comment]
Thanks a million! That helped a lot
