### ISSUE TITLE
Monitor does not show in IE11

### ISSUE THREAD

**Issue by stuartjsmith** [jan-molak/jenkins-build-monitor-plugin#288]
Hi,

looks like a javascript issue maybe, but the wallboard is not visible in IE11 - have tested on a couple of machines with the same result - a blank white screen. This was in version 1.11+build.201701152243, I am unable to check the latest version as I cannot install without a restart and can't do this easily, but looking at the changelog I cannot see anything related to this issue,

thanks

**Comment by jan-molak** [comment]
Thanks @stuartjsmith, is there any error that shows in the [browser's JavaScript console](https://msdn.microsoft.com/en-us/library/bg182326(v=vs.85).aspx)?

J

**Comment by stuartjsmith** [comment]
Hi, see below:

![image](https://cloud.githubusercontent.com/assets/2319633/22689410/d80cab80-ed28-11e6-94a7-2a2d6d8e49ee.png)

hope this helps, Stuart

**Comment by jan-molak** [comment]
Thanks Stuart, yes, it looks like IE11 doesn't support deleting properties on the `window` object.
I've added a workaround, but nevertheless, IE11 has a large number of CSS3 support-related bugs (especially around [`flexbox`](http://caniuse.com/#search=flexbox), which Build Monitor relies on), so if you have to use IE, I'd strongly suggest [upgrading to Edge](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support).
If you don't have to use IE, I'd suggest using Chrome.

**Comment by jan-molak** [comment]
Would you like to check the [latest build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/lastSuccessfulBuild/artifact/build-monitor-plugin/target/build-monitor-plugin.hpi) and see if it solves the problem for you?
