### ISSUE TITLE
Not visible subtitles (conflict with jenkins-material-theme)

### ISSUE THREAD

**Issue by khipis** [jan-molak/jenkins-build-monitor-plugin#291]
Hi!

There is small conflict while usage of jenkins-build-monitor-plugin with jenkins-material-theme.

![capture](https://cloud.githubusercontent.com/assets/12296044/22620246/b70f66f2-eb07-11e6-9868-9be8be9a704f.PNG)

Subtitles became unreadable.

We are able to fix that by adding to material-green.css

`
.build-monitor{
color:#fff!important;
}
`

becase we can manage this file through git but it will be nice to have that bundled in plugin maybe? (!important) 

Best regards and thanks for your work!

**Comment by jan-molak** [comment]
Hey and thanks for reporting this!

Would you like to submit a PR? Looks like you'd only need to apply the fix you already have to 
[build-monitor-plugin/src/main/webapp/less/theme/industrial.less](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/master/build-monitor-plugin/src/main/webapp/less/theme/industrial.less)

The file is empty now, but I'd like to eventually move all the css from [here](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/master/build-monitor-plugin/src/main/webapp/themes/industrial.css) to `.less` files.

All the best,
Jan
