### ISSUE TITLE
Build view includes google analytics from unknown source

### ISSUE THREAD

**Issue by sorenmalling** [jan-molak/jenkins-build-monitor-plugin#292]
Once completed a setup for display of builds, the following is found in the source code

```
ga('create', 'UA-61694827-4', 'auto', {
  'userId':     '[SYSTEM CREATED VALUE - HIDDEN HERE]',
  'sampleRate': 1
});
```

The used Google Analytics code, is not entered by me or anywhere to be found in the system configuration

**Comment by sorenmalling** [comment]
For people interested, the reason for the GA code is here

https://github.com/jan-molak/jenkins-build-monitor-plugin/commit/db28e1dd815ba4adf072f4673bb1a6178e9d2b73

You can disable the statistic from the Jenkins system configuration

**Comment by jan-molak** [comment]
Yes, the analytics are anonymous and optional, as per the [privacy policy](https://github.com/jan-molak/jenkins-build-monitor-plugin/wiki/Privacy-Policy).
