### ISSUE TITLE
"Sorry to bother you, but there is a slight issue ..." error

### ISSUE THREAD

**Issue by paveldudka** [jan-molak/jenkins-build-monitor-plugin#294]
After ~ 10 seconds after I open my build monitor view, I get a huge error popup saying: "Jenkins returned a "413" response causing the last request to fail. This usually means a network connection problem or that Jenkins is being restarted. Don't worry, reloading the page should help :-)"

Reloading page helps indeed, but after 10 seconds - the same error.

Build status is displayed correctly, though

**Comment by jan-molak** [comment]
Interesting, [`413`](http://www.checkupdown.com/status/E413.html) is quite a rare error and suggest that the browser is sending too much back to the server (?).

Could you check your javascript console and paste the request/response pair that's triggering the 413?

Thanks,
Jan

**Comment by paveldudka** [comment]
I think I am hitting this issue: https://issues.jenkins-ci.org/browse/JENKINS-36993

Just checked my requests and it turns out the size of my cookies is a bit over 8kb which apparently causes 413 errors. 

Issue is not related to this plugin, so closing it now.

Thanks a lot for a great plugin BTW! Lots of team @ Apple use it ;)

**Comment by jan-molak** [comment]
Haha, that's so great to hear! (says Jan, typing on his Mac)

If you have any photos that you can share, please feel to send them over to jan dot molak at smartcodeltd dot co dot uk 😄
