### ISSUE TITLE
Unable to obtain build-monitor-plugin from https://repo.jenkins-ci.org/public using Gradle

### ISSUE THREAD

**Issue by v-bu** [jan-molak/jenkins-build-monitor-plugin#299]
Hi,
I tried to obtain 'org.jenkins-ci.plugins:build-monitor-plugin:1.11+build.201701152243@hpi' as dependency from a Gradle build script. The dependency resolution failed since the associated pom file refers to the parent pom 'org.jenkins-ci.plugins:build-monitor:1.11+build.201701152243' not published in https://repo.jenkins-ci.org/public.  Did you publish the parent pom in a different repo?

**Comment by jan-molak** [comment]
Hey @v-bu! Can I ask about the scenario that requires you to use Build Monitor as a dependency?

**Comment by v-bu** [comment]
Hi @jan-molak, for Build Monitor we use the dependency to assemble our setup (jenkins + plugins + configuration + customization) into a rpm package. It's a convenient way of automatization. My current work around is to include the manually downloaded hpi file.

**Comment by jan-molak** [comment]
Gotcha, you could also `wget` a file from http://updates.jenkins-ci.org/latest/build-monitor-plugin.hpi

**Comment by th3w4y** [comment]
Hi @jan-molak, do you plan to fix the parent pom for this?

**Comment by stefanverhoeff** [comment]
We have the same issue, because this one is closed I opened #373

**Comment by js-timbirkett** [comment]
See https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/373 for a workaround.
