### ISSUE TITLE
Visualisation 0% and 100% progress

### ISSUE THREAD

**Issue by kpopv** [jan-molak/jenkins-build-monitor-plugin#306]
The progress shown is based on historical time, this has some consequences:

- long running jobs appear empty for a while, until the progress is far enough to show some of the pulsing color. It would be nice to show a minimum width to indicate the build has started

- if a job takes longer than before, the entire width of the job is filled. It would be nice to not fully fill the box, so to indicate the job is still running.

**Comment by jan-molak** [comment]
Hey @kpopv and thanks for your feedback! That sounds sesnsible, would you like to submit a pull request so we can continue this conversation over some code?

**Comment by dcendents** [comment]
Hi @kpopv , I agree it would be nice to limit the progress width to be less than 100%. 

I just want to note that I submitted a PR #301 which has been merged to address part of the problem, when the build reach 100% progress, it will still be animated so we can visually see it is still building. It should be part of the next release.

**Comment by kpopv** [comment]
@dcendents , I agree, PR #301 seems a good approach to make it clear that the project is still building.
