### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by vicyap** [jan-molak/jenkins-build-monitor-plugin#314]
Is there a functionality to customize the colors that are shown on the build monitor? I was able to track down this file (https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/master/build-monitor-plugin/src/main/webapp/less/module/progressbar.less) which shows the colors being used... but is it possible to add our own project states and colors?

**Comment by jan-molak** [comment]
Hey @vicyap! Not really, there's a discussion about custom themes [here](#135) though.
