### ISSUE TITLE
8 columns not enough

### ISSUE THREAD

**Issue by oscarfoley** [jan-molak/jenkins-build-monitor-plugin#315]
I love your plugin! It is awesome.
But I need more "Maximum number of columns". Values are 1 to 8 but I would really need 16 or so.

Do you think it is feasible to have that limit raised?
![capture](https://cloud.githubusercontent.com/assets/7723954/26591662/458d37f8-4556-11e7-8e56-5b5bbdc5375a.PNG)
?

Dekuju,
Oscar

**Comment by jan-molak** [comment]
Hey @oscarfoley, I'm glad that you find it useful :-)

Out of curiosity, how many builds are you thinking of displaying and what's your screen resolution?

Best,
Jan

**Comment by oscarfoley** [comment]
I had 24 builds on 8 columns in 3 rows in a big TV (42 inches) with 1600x1200 resolution , everything look cool. But  I added 3 builds more and couldn't have 9 columns x 3 rows...

**Comment by vanta** [comment]
@oscarfoley btw. did you consider splitting job into e.g. 3 different Build Monitor views and applying some browser plugin to rotate through all of them opened in separate tabs?

**Comment by dcendents** [comment]
@oscarfoley as a workaround: the setting is saved in a cookie. You can set the cookie value to any value you need (I've set it to 20 in one view).
