### ISSUE TITLE
Build monitor dashboard exits view and shows random Jenkins page from my Google chrome multi tab rolling views setup

### ISSUE THREAD

**Issue by ibata** [jan-molak/jenkins-build-monitor-plugin#317]
I have multiple dashboards that I bookmarked on google chrome. I am using a technic to have google roll through each tab to display the related dashboard, after 10 second for instance.
But sometime I catch one of my dashboard tab exiting  and showing a Jenkins page. Sometime a Jenkins build fail or pass page. It  looks like it is showing any random Jenkins page. It feels like there is a session or cookie issue or even a network issue since this behavior is only happening on one of tv screen that is connected by vpn/wifi . Other tv monitors are connected by wire to my laptop.

I also tested the dashboard with one tab only and there is no issue. So it seems like the combination of multiple tabs and vpn/wifi is triggering chrome tabs to stop showing the dashboard.

Any idea on how to address this please?

**Comment by jan-molak** [comment]
It's hard to tell without understanding the details of your network, to be honest...

As this is not happening when you don't use the tab switching technique, I'd say it's probably related to how the tabs are switched?

Jenkins does issue a session cookie and Build Monitor attaches that session cookie to every AJAX request it makes. However, sometimes you can come across a problem where there is a caching proxy in front of Jenkins that caches that cookie incorrectly. I'd say this might be a good first place to look.

If that's not it, try to open the chrome dev tools and record the network traffic, maybe that will point you in the right direction?

Hope that helps!
Jan

**Comment by ibata** [comment]
You are so helpful. I will investigate that  

Regards
Luc iBata
