### ISSUE TITLE
Fix broken link in README

### ISSUE THREAD

**Issue by Abrasha** [jan-molak/jenkins-build-monitor-plugin#319]
Link to the tests is broken: https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/master/src/test/java/com/smartcodeltd/jenkinsci/plugins

## (A)TDD

If you'd like to understand more about the logic behind the Build Monitor Plugin,
have a look at the [tests that drove the design](/src/test/java/com/smartcodeltd/jenkinsci/plugins/).

**Comment by vkotovv** [comment]
I've created a PR for that: #323
