### ISSUE TITLE
[Feature Request]Show all/running builds in same job

### ISSUE THREAD

**Issue by kspoonab** [jan-molak/jenkins-build-monitor-plugin#320]
Hi all, 
I love this plugin so much!
But when I running the same job twice, it will only show the latest build.
Wonder if there is a option that show all/running builds in one job.
Thank you so much!

**Comment by kspoonab** [comment]
Love the new design in 1.12!
Will close this issue

**Comment by jan-molak** [comment]
Great stuff, I'm glad you like it!
