### ISSUE TITLE
Have some problems with version 1.12+build.201704111018

### ISSUE THREAD

**Issue by dsoguet** [jan-molak/jenkins-build-monitor-plugin#322]

**Comment by dsoguet** [comment]
For info I'm updating my Jenkins plugins and I encounter a problem with build-monitor-plugin version 1.12+build.201704111018. After updated it and its related plugins my Gitlab webhook displays a error 500 message, and builds generates very strangely (run several times, very long...)

Does someone have the same problem ?

After investigation seems that it is linked to the depencendy plugin mq-notifier

Before the update my conf was (for the plugins which have changed after the update)
Jenkins 2.46.3
build-monitor-plugin 1.11+build.201701152243
build-failure-analyzer 1.18.1
email-ext 2.57.1
gerrit-trigger 2.23.0
mq-notifier 1.2.1

After the update
Jenkins 2.46.3
build-monitor-plugin 1.12+build.201704111018
build-failure-analyzer 1.19.0
email-ext 2.57.2
gerrit-trigger no more installed (sounds strange but it is the result)
mq-notifier 1.2.3

If I come back (with a snapshot) to my old conf and I update only mq-notifier I obtain the same problem

Thanks in advance if someone has an idea

**Comment by dsoguet** [comment]
So I confirm my doubts about mq-notifier plugin version 1.2.3

Instead of installing with Jenkins CLI the different plugins I have installed them manually with the GUI, except mq-notifier.
Everything worked correctly (note that at the end of the process gerrit-trigger is installed in version 2.23.3)

Then I have installed with the GUI mq-notifier and had again the problem with gitlab webhook and builds

**Comment by jan-molak** [comment]
Hey @dsoguet; Build Monitor doesn't use mq-notifier; I suppose it could be a dependency of one of the other plugins that Build Monitor can work with.
