### ISSUE TITLE
The Build number section pushes the Job title off the screen if the pipeline job has parallel executions in a Stage

### ISSUE THREAD

**Issue by ryanbland** [jan-molak/jenkins-build-monitor-plugin#329]
It looks like the Stage that is running gets displayed in the section with the build number, however when the stage has parallel executions the same stage name is repeated over and over again, which if the stage name is long enough, will push the entire tile to the right and off the screen. 

The below image shows what it looks like after I changed the name of the stage from a Longer string to a single word
![image](https://user-images.githubusercontent.com/23195256/28899544-50639298-77b1-11e7-8d4d-09585d414157.png)

**Comment by ChadiEM** [comment]
Hi @ryanbland, thanks for reporting this!

Do you have something like the below?
```
stage("Tests") {
    steps {
        parallel (
            "first" : {
                // ...
            },
            "second" : {
                // ...
            }, //etc
        )
    }
}
```
Otherwise, can you please show a dummy example of what your parallelism looks like?

**Comment by ryanbland** [comment]
Hi @ChadiEM 
My scripts are similar except I am not doing 'steps'. It looks like this
`stage("Tests") {
        parallel (
            "first" : {
                // ...
            },
            "second" : {
                // ...
            }, //etc
        )
}`

**Comment by jan-molak** [comment]
Hey @ryanbland, would you mind checking if that [latest build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/lastSuccessfulBuild/artifact/build-monitor-plugin/target/build-monitor-plugin.hpi) solves the issue for you? Thanks!

**Comment by ryanbland** [comment]
Sorry about the late response, but it is now working as expected.
