### ISSUE TITLE
Question - committers not showing - what is required to display that?

### ISSUE THREAD

**Issue by toavinaandria** [jan-molak/jenkins-build-monitor-plugin#344]
We are using Github as our SCM and pipelines. Committers are not showing despite ticking the option. Is there anything that needs to be enabled for this to work? Perhaps a minor doc. could help if this a widely known issue but after Googling I could not find anything

**Comment by erikhakansson** [comment]
Known issue. Here's my PR for the fix:

https://github.com/jan-molak/jenkins-build-monitor-plugin/pull/293

You could build that locally and install manually into your Jenkins.

**Comment by toavinaandria** [comment]
Thanks a lot!
