### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by LJBD** [jan-molak/jenkins-build-monitor-plugin#351]
Hello!

We've been using your great plugin to display build statuses of freestyle jobs for quite some time and it's great! However, we've recently switched to Pipelines and I've noticed that Build Monitor 1.12 doesn't display statuses of their stages.
After a while of digging, I've stumbled across #286 it seems that our needs have been met already. So, when can we expect a new release of your plugin to enjoy monitoring pipelines?

Best regards,
Łukasz

**Comment by jan-molak** [comment]
Hi Łukasz and thanks for your kind words! Apologies, the last couple of months have been a bit hectic and I didn't get to spend any time on Build Monitor. I've just pushed the latest build to the Jenkins registry, so hopefully the features you're after should be with you shortly!

Best,
Jan

**Comment by jan-molak** [comment]
e
