### ISSUE TITLE
No CI builds?

### ISSUE THREAD

**Issue by jakub-bochenski** [jan-molak/jenkins-build-monitor-plugin#367]
I wanted to download a build of  #365 to try out the fix but I can't find any

Most of Jenkins plugins have builds on ci.jenkins.io [(example)](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Flogstash-plugin/activity/)

I couldn't find any recent builds on https://smartcode-opensource.ci.cloudbees.com/ either

**Comment by jan-molak** [comment]
#365 is included in the most recent CI build, which you should be [able to download](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/113/) now.
