### ISSUE TITLE
Unable to include jenkins-build-monitor-plugin as dependency because of missing parent POM for jenkins-build-monitor

### ISSUE THREAD

**Issue by stefanverhoeff** [jan-molak/jenkins-build-monitor-plugin#373]
This issue is similar to #299 and [JENKINS-43171](https://issues.jenkins-ci.org/browse/JENKINS-43171).

We're using the [Job DSL plugin](https://github.com/jenkinsci/job-dsl-plugin) and [Gradle Jenkins Job DSL plugin](https://github.com/heremaps/gradle-jenkins-jobdsl-plugin) to automatically create Jenkins jobs. To generate the right XML, the Job DSL plugin uses the Jenkins plugin as dependency.

We are using Gradle to include dependencies, when we run Gradle it complains the parent POM is missing:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':jenkinsPlugins'.
> Could not resolve org.jenkins-ci.plugins:build-monitor-plugin:1.12+build.201708172343.
  Required by:
      project :
   > Could not resolve org.jenkins-ci.plugins:build-monitor-plugin:1.12+build.201708172343.
      > Could not parse POM https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/build-monitor-plugin/1.12+build.201708172343/build-monitor-plugin-1.12+build.201708172343.pom
         > Could not find org.jenkins-ci.plugins:build-monitor:1.12+build.201708172343.
           Searched in the following locations:
               https://repo1.maven.org/maven2/org/jenkins-ci/plugins/build-monitor/1.12+build.201708172343/build-monitor-1.12+build.201708172343.pom
               https://repo1.maven.org/maven2/org/jenkins-ci/plugins/build-monitor/1.12+build.201708172343/build-monitor-1.12+build.201708172343.jar
               https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/build-monitor/1.12+build.201708172343/build-monitor-1.12+build.201708172343.pom
               https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/build-monitor/1.12+build.201708172343/build-monitor-1.12+build.201708172343.jar
               https://plugins.gradle.org/m2/org/jenkins-ci/plugins/build-monitor/1.12+build.201708172343/build-monitor-1.12+build.201708172343.pom
               https://plugins.gradle.org/m2/org/jenkins-ci/plugins/build-monitor/1.12+build.201708172343/build-monitor-1.12+build.201708172343.jar
```

This is the snippet of Gradle code where we include the plugin:
```
dependencies {
...
    jenkinsPlugins 'org.jenkins-ci.plugins:build-monitor-plugin:1.12+build.201708172343'
...
}
```

Indeed the parent POM is not in the Jenkins maven repository. Fix could be to either publish the parent POM or to refactor the plugin POM (this is suggested in [JENKINS-43171](https://issues.jenkins-ci.org/browse/JENKINS-43171)). Internally we have published the plugin and parent POMs in our private maven repository.

**Comment by GhaTMA** [comment]
+1

**Comment by jan-molak** [comment]
Hi there,

I'm happy to publish the parent pom if that helps? Alternatively if someone wants to propose a PR to refactor the plugin POM I'd be happy to consider that option.

Jan

**Comment by stefanverhoeff** [comment]
Hi @jan-molak, thanks for the response. Publishing the parent POM would be the easiest fix now and can fix the issue retroactively for existing versions.

Meanwhile I'll try to do a refactoring on the POM structure.

**Comment by sebastiangraf** [comment]
PR #374 is done and reviewed, any please to merge this? We are facing broken builds each time this plugin is updated.

**Comment by starwarsfan** [comment]
Any news here? Any other open points regarding #374? The problem still exists!

**Comment by starwarsfan** [comment]
More than four months...

Any news at this topic?

**Comment by jan-molak** [comment]
Hey @stefanverhoeff - you're right, it's been a good couple of months since I had the capacity to look at the tickets and PRs you guys have raised. In that time the CloudBees Dev@Cloud service I used for Build Monitor has also [ceased to exist](https://support.cloudbees.com/hc/en-us/articles/360008971551-DEV-cloud-End-of-Life), which means that I'll need to set up the pipeline from scratch again somewhere else.

**Comment by stefanverhoeff** [comment]
Hi @jan-molak , no worries. For publishing the parent POM at least no extra CI should be needed? Or was that part automated on Dev@Cloud?

**Comment by thelfter** [comment]
Any update regarding to this?

**Comment by Vincevrp** [comment]
@jan-molak this is still broken in 2020... Is there any update regarding this?

**Comment by amisuna** [comment]
Any news?

**Comment by js-timbirkett** [comment]
I think you guys broke @jan-molak... I encountered this today (as well as a few years ago) and came up with a reasonable workaround...

# Workaround

Something like this in your `build.gradle` will get things working:

1. Add the download plugin to: 
```
plugins {
    id 'groovy'
    id 'de.undercouch.download' version '4.1.1'
}
```

2. Add a version variable and a download task to our `build.gradle` like:  
```
def buildMonitorVersion = '1.12+build.201809061734'
...
...
task downloadBuildMonitorPlugin(type: Download) {
    src "https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/build-monitor-plugin/${buildMonitorVersion}/build-monitor-plugin-${buildMonitorVersion}.hpi"
    dest new File(sourceSets.test.output.resourcesDir, "pluginDownloads/build-monitor-plugin-${buildMonitorVersion}.hpi")
    onlyIfModified true
}
```

3. Amend the `resolveJenkinsPlugins` task to depend on downloads and copy the file.
```
task resolveJenkinsPlugins(type: Copy) {
    dependsOn tasks.withType(Download)

    from configurations.jenkinsPlugins
    include '*.hpi'
    include '*.jpi'
    into new File(sourceSets.test.output.resourcesDir, 'test-dependencies')

    from new File(sourceSets.test.output.resourcesDir, 'pluginDownloads')
    include '*.hpi'
    include '*.jpi'
    into new File(sourceSets.test.output.resourcesDir, 'test-dependencies')

    doLast {
        def baseNames = source.collect { it.name[0..it.name.lastIndexOf('.')-1] }
        new File(destinationDir, 'index').setText(baseNames.join('\n'), 'UTF-8')
    }
}
```

> _But Tim, why not download straight to the test-dependencies directory?_ Well, the `resolveJenkinsPlugins` task creates a file `index` which is used to load the plugins. If there isn't the second copy of the file in the `resolveJenkinsPlugins` task, then the task never knows about thee file to generate that index file.

## Hoorah! You should now have either: working tests OR broken tests OR your next problem to solve :) - Hope someone finds this useful.
