### ISSUE TITLE
Plugin Missing from Jenkins SIte

### ISSUE THREAD

**Issue by ianlunam** [jan-molak/jenkins-build-monitor-plugin#381]
Plugin disappeared from jenkins plugin site, 404 for https://plugins.jenkins.io/build-monitor-plugin

```
    amazon-ebs: build-monitor-plugin is neither a valid file, URL, nor a plugin artifact name in the update center
    amazon-ebs: build-monitor-plugin looks like a short plugin name. Did you mean ‘build-keeper-plugin’?
```

**Comment by clive-hetzner** [comment]
I came here to report the same.

**Comment by ichikata** [comment]
bump, i'm having the same issue

```================================================================================
    Error executing action `install` on resource 'jenkins_plugin[build-monitor-plugin]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass```

**Comment by jan-molak** [comment]
Thanks for letting me know. I just checked now and it all seems OK? Perhaps a temporary glitch on jenkins.io?

<img width="1308" alt="screen shot 2018-06-28 at 01 47 46" src="https://user-images.githubusercontent.com/1089173/42007022-6163b6dc-7a75-11e8-85aa-72a491b84408.png">

**Comment by yuriron** [comment]
Seems to work fine now, but looks like the last release doesnt reflect the last build (1.12+build.201806131​034) - is that on porpuse?

**Comment by ianlunam** [comment]
Closing as it's automagically returned.
