### ISSUE TITLE
problem access to jenkins monitor pro

### ISSUE THREAD

**Issue by ybello33** [jan-molak/jenkins-build-monitor-plugin#388]
Hi all
**backgoud**
- our jenkins url is configured to work with port 8080 with our domain (not using the http://localhost:8080) 
I also download the Jenkins monitor pro plugin and installed 

Right now i can;t access into the dashboard beacuse the plugin is rrequired to work with localhost only

any suggesting how i can configure the plugin to work with our url 

i'm getting this error  
xxx.xxx.com:8080 says
Connection to Jenkins Fails. Check the connection settings.

any help please on this .. -10x

**Comment by ybello33** [comment]
Hello .. any update ?

**Comment by ybello33** [comment]
i didn;'t got any final solution

**Comment by OsmelLavalier** [comment]
leaving a comment in case this gets reopened
