### ISSUE TITLE
Text scale broken

### ISSUE THREAD

**Issue by vlazdra** [jan-molak/jenkins-build-monitor-plugin#390]
Hi, so I have updated the version of the plugin to 1.12+build.201809041621 and with the update the Text scale slider is broken.

Instead of changing the scale of the entire block with the title and subtitle and the rest of elements, it changes the scale only for the subtitle, the title stays unchanged.

Please let me know if I can be of more assistance in resolving this issue.

**Comment by jlone** [comment]
I am noticing the same issue. Hopefully it is fixed soon :)

**Comment by jan-molak** [comment]
Hey guys, would you mind checking if clearing the cookies and reloading the view addresses the issue?

**Comment by jlone** [comment]
I cleared cookies and cache but still having the same issue. Google Chrome, Firefox and IE browsers all have the same result.

**Comment by jan-molak** [comment]
@jlone - thanks; I reverted the change that seems that affected the slider. The new build should hit the update centre shortly.

**Comment by jlone** [comment]
@jan-molak thanks, it took a while to hit the update centre but after getting that version we are back to normal now.

**Comment by vlazdra** [comment]
I can confirm that the update has fixed the issue.
There was no need for any cookie cleanup whatsoever. 👍

**Comment by jan-molak** [comment]
Thanks for letting me know! I'm glad it's working fine for you now.
