### ISSUE TITLE
Text scale no longer scaling text

### ISSUE THREAD

**Issue by Kregap** [jan-molak/jenkins-build-monitor-plugin#391]
## Overview
After last (yesterdays) plugin release text scaling is no longer scaling the text. Seems like it is only scaling margins/paddings or something controlling distance between text and cell border.
![build monitor](https://user-images.githubusercontent.com/15647621/45205147-9c715b00-b281-11e8-9f3c-e8b88f5f2f94.gif)

## Test environment

- Jenkins ver. 2.121.3
- Jenkins Build Monitor Plugin v1.12+build.201809061734
- Chrome Version 68.0.3440.106 (Official Build) (64-bit)
- Safari Version 11.1.2 (13605.3.8)
- Firefox 62.0 (64-Bit)

**Comment by jannekem** [comment]
Probably caused by this change https://github.com/jan-molak/jenkins-build-monitor-plugin/pull/382 as vw is relative to the viewport size instead of font size.

**Comment by Kregap** [comment]
In my case we have one monitor which is displaying all existing PRs jobs, so scaling it down helped with fitting more while still being readable. I don't know what was the original reason behind the slider and wouldn't mind if it would be done differently. Maybe it helped because people are using completely different devices with different pixel to physical point size ratio so I guess you cannot do it well for everyone without manual adjustment option, but I'm not sure, I have just basic understanding of web tehcnologies. :)

**Comment by Kregap** [comment]
Ok, I just cheked. With todays release it is fixed. Probably due to mentioned ticket #390.
