### ISSUE TITLE
Number of columns configurable

### ISSUE THREAD

**Issue by MarkTickner** [jan-molak/jenkins-build-monitor-plugin#409]
We use this plugin in our automated jenkins deployment, which means that any config not persisted is lost. The 'number of columns' is stored as a cookie which makes it impossible to automate. Could there be a default value for this to be set to in the Configure screen?

**Comment by timbrown5** [comment]
+1, we are looking to do the same thing. Could this also include a default for text size (as in our case it's huge on our TV).

**Comment by timbrown5** [comment]
Added a pull request:
https://github.com/jan-molak/jenkins-build-monitor-plugin/pull/419

**Comment by hmatejx** [comment]
This is a must have, especially if you use this view in a dashboard you don't have full control of (e.g. you can only provide an URL).
