### ISSUE TITLE
Host on jenkins ci?

### ISSUE THREAD

**Issue by timja** [jan-molak/jenkins-build-monitor-plugin#418]
Is there any reason this isn't hosted with the rest of the plugins on the jenkinsci github org?

https://jenkins.io/doc/developer/publishing/requesting-hosting/

@jan-molak

**Comment by jan-molak** [comment]
@timja - historical decision. When I released Build Monitor for the first time it's test and release process was quite different to all the other Jenkins plugins. For example, Build Monitor uses semantic versioning and its CI process involves running end-to-end acceptance tests (that I don't think any other plugin does).

CloudBees Dev@Cloud offered flexibility that I needed back then.

Now that CloudBees no longer support Dev@Cloud I'm happy to revisit this decision.

**Comment by timja** [comment]
That makes sense, I think it would be good to move to the Jenkins ci GitHub organisation 

When anyone searches for compatibility changes they normally only search Jenkinsci
GitHub publishing of docs to the plugin site are only supported on the jenkinsci org 
There’s free Jenkins ci on it as well

You would just need to file a hosting request in the Jenkins jira and ask for a transfer instead of a fork

**Comment by oleg-nenashev** [comment]
To add more justification for the migration, we recently introduced support of plugin docs from GitHub: https://groups.google.com/forum/#!topic/jenkinsci-dev/VSdfVMDIW-A . It works only for plugins under `jenkinsci`

**Comment by oleg-nenashev** [comment]
@jan-molak If you are ready to move, I can help with transfer so that we can retain GitHub issues and Full requests flawlessly

**Comment by oleg-nenashev** [comment]
Update here: We had a discussion with @jan-molak today, and the decision is to NOT do the transfer for now. I am happy to help if the decision is revisited at some point

**Comment by jan-molak** [comment]
Closing as I'm now planning to migrate the plugin to Jenkins CI org, with kind support from @basil
