### ISSUE TITLE
Option to show result breakdown for matrix builds

### ISSUE THREAD

**Issue by trejkaz** [jan-molak/jenkins-build-monitor-plugin#47]
We use matrix builds to run tests and build releases across multiple platforms. Sometimes a build only fails on one platform, making the entire result red.

Although this is certainly the case with Jenkins itself as well, showing the whole build as red when really only a fraction of it failed, doesn't really give a good impression of how stable the build is. The common scenario in our case is that Windows is stable and Mac and Linux are unstable (because development is still in progress for those ports.) This results in the whole build being unstable, which then shows up on the build monitor as "failed" because it still doesn't differentiate between the two states.

A lot of the time, the failure on that one slave occurs just because the slave it ran on had a configuration issue. It's nice to know which platform it was, because it can affect which developer will be investigating the issue.

Being able to see the progress of each build independently would also be rather nice. It might not even be necessary to show which build is which, as long as the order of them is stable (which I think in Jenkins it is.)

**Comment by jan-molak** [comment]
Thanks for your feedback, @trejkaz. Let's move this conversation to #62 as it has proposed code changes.
