### ISSUE TITLE
Unable to display the jobs when not authenticated

### ISSUE THREAD

**Issue by beraneck** [jan-molak/jenkins-build-monitor-plugin#6]
Hello !

The build monitor view works perfectly when I'm authenticated. 
But It only shows the title and settings button when I'm not authenticated. 
On our server, anonymous users can see the jobs on the standard Jenkins UI.

Our configuration :
Jenkins ver. 1.526 
Authentication is done by Atlassian Crowd with matrix based access right.

Anonymous users have the following rights : 
Global : read
Slave : nothing
Job : read + discover
Views : Read
Version : nothing

Thanks
Best Regards
Nicolas

**Comment by jan-molak** [comment]
Closing the ticket as it seems that the described problem is solved with an upgraded Crowd2 plugin.
