### ISSUE TITLE
Feature request: allow customizing the default settings

### ISSUE THREAD

**Issue by patrickdepinguin** [jan-molak/jenkins-build-monitor-plugin#71]
The plugin has a fixed default configuration, and stores user-made changes in a cookie. This works fine when displaying the build monitor view on a controllable display.
However, when displaying it on a system without keyboard/mouse, like a web kiosk, modifying the configuration so it would be stored in the cookie is problematic.
Being able to set the default configuration in absence of a cookie could cover this scenario.
I currently worked around this by manually editing the javascript files, but this is not very nice.
##

**Comment by jan-molak** [comment]
Looks like #189 could cover this scenario.

**Comment by patrickdepinguin** [comment]
Yes looks like it, consider this issue and that pr coupled!

**Comment by jan-molak** [comment]
Cool, cheers, will do ;-)
