### ISSUE TITLE
Feature request: Multi-configuration projects

### ISSUE THREAD

**Issue by rubdos** [jan-molak/jenkins-build-monitor-plugin#85]
Some of my projects are multi-configuration projects. I'm building C++ applications for different platforms and architectures (platforms: android, linux, windows and archs: 32 and 64 bit), excluding nonsense combinations (android 64 bit isn't yet out AFAIK).
I'd love to see the project be split in some ways and see the current matrix-element being build lit up, instead of the whole project at once. That way you can also see what sub-build breaks and what doesn't.

**Comment by jan-molak** [comment]
Thanks @patrickdepinguin - let's move this conversation to #62
