### ISSUE TITLE
Feature request: order by failed, unstable and successful.

### ISSUE THREAD

**Issue by shakesoftware** [jan-molak/jenkins-build-monitor-plugin#86]
Make failed build be in first line, next the unstable builds, and only at the bottom the successful builds.
Group by color when red is up, yellow after, and green down.

Thanks,

**Comment by saan800** [comment]
This would be a great, having the failing builds at the top would make this plugin even easier to monitor

**Comment by jan-molak** [comment]
Hi guys and thanks for your feedback! This could be achieved with a custom comparator.
Perhaps you'd like to submit a pull request?

Custom comparators should be fairly straight-forward to add, have a look at #113 and [this commit](https://github.com/jan-molak/jenkins-build-monitor-plugin/commit/d01494c3b776de6b4048a95da580af8eb1e88027).
