### ISSUE TITLE
Show disabled jobs in grey

### ISSUE THREAD

**Issue by clee-jana** [jan-molak/jenkins-build-monitor-plugin#90]
Hi Jan,

Big fan of the build monitor plugin. It would be nice if it showed disabled jobs in grey perhaps?

Thanks,
Chris

**Comment by ychrysler** [comment]
This would be a handy feature for us too in order to avoid false negatives.
Be happy to help out with coding if someone can point us in the right direction of which classes/scripts need to be modified.
