### ISSUE TITLE
Show tests passed/failed for Jobs executing tests

### ISSUE THREAD

**Issue by benoit808** [jan-molak/jenkins-build-monitor-plugin#99]
The Radiator View plug-in does that but I would love to see it in the Build Monitor plug-in

**Comment by sanga** [comment]
+1. Would be cool to have this

**Comment by patrickdepinguin** [comment]
Actually, I think this has been covered with my changes in the Build Failure Analyzer plugin. If you install that plugin, and enable JUnit parsing in its configuration, then failed test cases will be shown on the Build Monitor automatically.
So I actually think this issue can be closed. Maybe the Build Monitor documentation can explicitly mention this feature.

**Comment by jan-molak** [comment]
@patrickdepinguin - documentation updated as per your comment: https://github.com/jan-molak/jenkins-build-monitor-plugin/wiki/FAQ

Thanks!

**Comment by benoit808** [comment]
@jan-molak This solution doesn't seem to work for me and I am not sure if this is due to a change to the Build Analyzer plugin or misconfiguration on my side.
I installed the plugin and went to Manage Jenkins > Configure Jenkins and then looked under "Build failure analyzer" and there is no option to "Enable JUnit parsing"

**Comment by patrickdepinguin** [comment]
Which version of build failure analyzer did you install?

**Comment by benoit808** [comment]
I have version 1.13.0 for Build failure analyzer

**Comment by patrickdepinguin** [comment]
The exact wording of the option is: "Treat failed test cases (as indicated by JUnit/xUnit/... publishers) as failure causes.", it is right below 'Concurrent scans' in version 1.13.0. I'm using the same version of Build Failure Analyzer with that feature enabled, without issue.
